project_id = "kiogiyemoqbnuvclneoe"

[functions.generate-sitemap]
verify_jwt = false

[functions.translate-slugs]
verify_jwt = false

[functions.translate-blog-posts]
verify_jwt = false

[functions.translate-testimonials]
verify_jwt = false

[functions.setup-admin-account]
verify_jwt = false
