project_id = "kiogiyemoqbnuvclneoe"

[functions.generate-sitemap]
verify_jwt = false

[functions.translate-slugs]
verify_jwt = false

[functions.translate-blog-posts]
verify_jwt = false

[functions.generate-article-images]
verify_jwt = false

[functions.translate-testimonials]
verify_jwt = false

[functions.setup-admin-account]
verify_jwt = false


[functions.design-home]
verify_jwt = false

[functions.social-listening]
verify_jwt = false

[functions.property-share]
verify_jwt = false
