project_id = "kiogiyemoqbnuvclneoe"

[functions.subscribe-newsletter]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.extract-page-texts]
verify_jwt = false

[functions.comprehensive-text-extract]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.map-proxy]
verify_jwt = false