/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AiPropertySearchRouteImport } from './routes/ai-property-search'
import { Route as AliKaranRouteImport } from './routes/ali-karan'
import { Route as AntalyaRouteImport } from './routes/antalya'
import { Route as ApartmentsForSaleInTurkeyRouteImport } from './routes/apartments-for-sale-in-turkey'
import { Route as BaliRouteImport } from './routes/bali'
import { Route as ContactThankYouRouteImport } from './routes/contact-thank-you'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CyprusRouteImport } from './routes/cyprus'
import { Route as DesignYourHomeRouteImport } from './routes/design-your-home'
import { Route as DubaiRouteImport } from './routes/dubai'
import { Route as InformationRouteImport } from './routes/information'
import { Route as IstanbulRouteImport } from './routes/istanbul'
import { Route as LuxuryVillasInTurkeyRouteImport } from './routes/luxury-villas-in-turkey'
import { Route as MapSearchRouteImport } from './routes/map-search'
import { Route as MersinRouteImport } from './routes/mersin'
import { Route as OffPlanPropertyTurkeyRouteImport } from './routes/off-plan-property-turkey'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PropertyForSaleInTurkeyRouteImport } from './routes/property-for-sale-in-turkey'
import { Route as PropertyGalleryRouteImport } from './routes/property-gallery'
import { Route as PropertyWizardRouteImport } from './routes/property-wizard'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TurkishCitizenshipByInvestmentRouteImport } from './routes/turkish-citizenship-by-investment'
import { Route as WizardThankYouRouteImport } from './routes/wizard-thank-you'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAboutUsRouteImport } from './routes/$locale/about-us'
import { Route as LocaleAiPropertySearchRouteImport } from './routes/$locale/ai-property-search'
import { Route as LocaleAliKaranRouteImport } from './routes/$locale/ali-karan'
import { Route as LocaleAntalyaRouteImport } from './routes/$locale/antalya'
import { Route as LocaleApartmentsForSaleInTurkeyRouteImport } from './routes/$locale/apartments-for-sale-in-turkey'
import { Route as LocaleBaliRouteImport } from './routes/$locale/bali'
import { Route as LocaleContactThankYouRouteImport } from './routes/$locale/contact-thank-you'
import { Route as LocaleContactUsRouteImport } from './routes/$locale/contact-us'
import { Route as LocaleCyprusRouteImport } from './routes/$locale/cyprus'
import { Route as LocaleDesignYourHomeRouteImport } from './routes/$locale/design-your-home'
import { Route as LocaleDubaiRouteImport } from './routes/$locale/dubai'
import { Route as LocaleInformationRouteImport } from './routes/$locale/information'
import { Route as LocaleIstanbulRouteImport } from './routes/$locale/istanbul'
import { Route as LocaleLuxuryVillasInTurkeyRouteImport } from './routes/$locale/luxury-villas-in-turkey'
import { Route as LocaleMapSearchRouteImport } from './routes/$locale/map-search'
import { Route as LocaleMersinRouteImport } from './routes/$locale/mersin'
import { Route as LocaleOffPlanPropertyTurkeyRouteImport } from './routes/$locale/off-plan-property-turkey'
import { Route as LocaleOurStoryRouteImport } from './routes/$locale/our-story'
import { Route as LocalePropertyForSaleInTurkeyRouteImport } from './routes/$locale/property-for-sale-in-turkey'
import { Route as LocalePropertyGalleryRouteImport } from './routes/$locale/property-gallery'
import { Route as LocalePropertyWizardRouteImport } from './routes/$locale/property-wizard'
import { Route as LocaleTestimonialsRouteImport } from './routes/$locale/testimonials'
import { Route as LocaleTurkishCitizenshipByInvestmentRouteImport } from './routes/$locale/turkish-citizenship-by-investment'
import { Route as LocaleWizardThankYouRouteImport } from './routes/$locale/wizard-thank-you'
import { Route as SegmentIdRouteImport } from './routes/$segment.$id'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAiInsightsRouteImport } from './routes/admin/ai-insights'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSocialListeningRouteImport } from './routes/admin/social-listening'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ArticlesExpensesBuyingPropertyTurkeyRouteImport } from './routes/articles.expenses-buying-property-turkey'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as LocaleSegmentIdRouteImport } from './routes/$locale.$segment.$id'
import { Route as LocaleArticleIdRouteImport } from './routes/$locale/article.$id'
import { Route as LocaleArticlesSlugRouteImport } from './routes/$locale/articles.$slug'
import { Route as LocaleArticlesExpensesBuyingPropertyTurkeyRouteImport } from './routes/$locale/articles.expenses-buying-property-turkey'
import { Route as LocaleCoursesIndexRouteImport } from './routes/$locale/courses.index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics.index'
import { Route as AdminAnalyticsEmailRouteImport } from './routes/admin/analytics.email'
import { Route as AdminAnalyticsHeatmapRouteImport } from './routes/admin/analytics.heatmap'
import { Route as AdminAnalyticsLeadsRouteImport } from './routes/admin/analytics.leads'
import { Route as AdminAnalyticsPropertiesRouteImport } from './routes/admin/analytics.properties'
import { Route as AdminAnalyticsRealtimeRouteImport } from './routes/admin/analytics.realtime'
import { Route as AdminAnalyticsTrafficRouteImport } from './routes/admin/analytics.traffic'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog.index'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog.$id'
import { Route as AdminBlogAiRouteImport } from './routes/admin/blog.ai'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog.new'
import { Route as AdminCrmIndexRouteImport } from './routes/admin/crm.index'
import { Route as AdminCrmContactsRouteImport } from './routes/admin/crm.contacts'
import { Route as AdminCrmTasksRouteImport } from './routes/admin/crm.tasks'
import { Route as AdminEmailIndexRouteImport } from './routes/admin/email.index'
import { Route as AdminEmailInboxRouteImport } from './routes/admin/email.inbox'
import { Route as AdminEmailSubscribersRouteImport } from './routes/admin/email.subscribers'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin/email.templates'
import { Route as AdminOfficeDocumentsRouteImport } from './routes/admin/office.documents'
import { Route as AdminOfficeSpreadsheetRouteImport } from './routes/admin/office.spreadsheet'
import { Route as AdminPresentationsIndexRouteImport } from './routes/admin/presentations.index'
import { Route as AdminPresentationsIdRouteImport } from './routes/admin/presentations.$id'
import { Route as AdminPropertiesIndexRouteImport } from './routes/admin/properties.index'
import { Route as AdminPropertiesNewRouteImport } from './routes/admin/properties.new'
import { Route as CoursesCountryIndexRouteImport } from './routes/courses.$country.index'
import { Route as CoursesCountryModuleSlugRouteImport } from './routes/courses.$country.$moduleSlug'
import { Route as CoursesCountryFinalExamRouteImport } from './routes/courses.$country.final-exam'
import { Route as LocaleCoursesCountryIndexRouteImport } from './routes/$locale/courses.$country.index'
import { Route as LocaleCoursesCountryModuleSlugRouteImport } from './routes/$locale/courses.$country.$moduleSlug'
import { Route as LocaleCoursesCountryFinalExamRouteImport } from './routes/$locale/courses.$country.final-exam'
import { Route as AdminCrmLeadsIndexRouteImport } from './routes/admin/crm.leads.index'
import { Route as AdminCrmLeadsIdRouteImport } from './routes/admin/crm.leads.$id'
import { Route as AdminEmailCampaignsIndexRouteImport } from './routes/admin/email.campaigns.index'
import { Route as AdminEmailCampaignsIdRouteImport } from './routes/admin/email.campaigns.$id'
import { Route as AdminEmailCampaignsNewRouteImport } from './routes/admin/email.campaigns.new'
import { Route as AdminPropertiesIdIndexRouteImport } from './routes/admin/properties.$id.index'
import { Route as AdminPropertiesIdEditRouteImport } from './routes/admin/properties.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPropertySearchRoute = AiPropertySearchRouteImport.update({
  id: '/ai-property-search',
  path: '/ai-property-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AliKaranRoute = AliKaranRouteImport.update({
  id: '/ali-karan',
  path: '/ali-karan',
  getParentRoute: () => rootRouteImport,
} as any)
const AntalyaRoute = AntalyaRouteImport.update({
  id: '/antalya',
  path: '/antalya',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsForSaleInTurkeyRoute =
  ApartmentsForSaleInTurkeyRouteImport.update({
    id: '/apartments-for-sale-in-turkey',
    path: '/apartments-for-sale-in-turkey',
    getParentRoute: () => rootRouteImport,
  } as any)
const BaliRoute = BaliRouteImport.update({
  id: '/bali',
  path: '/bali',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactThankYouRoute = ContactThankYouRouteImport.update({
  id: '/contact-thank-you',
  path: '/contact-thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CyprusRoute = CyprusRouteImport.update({
  id: '/cyprus',
  path: '/cyprus',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignYourHomeRoute = DesignYourHomeRouteImport.update({
  id: '/design-your-home',
  path: '/design-your-home',
  getParentRoute: () => rootRouteImport,
} as any)
const DubaiRoute = DubaiRouteImport.update({
  id: '/dubai',
  path: '/dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationRoute = InformationRouteImport.update({
  id: '/information',
  path: '/information',
  getParentRoute: () => rootRouteImport,
} as any)
const IstanbulRoute = IstanbulRouteImport.update({
  id: '/istanbul',
  path: '/istanbul',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxuryVillasInTurkeyRoute = LuxuryVillasInTurkeyRouteImport.update({
  id: '/luxury-villas-in-turkey',
  path: '/luxury-villas-in-turkey',
  getParentRoute: () => rootRouteImport,
} as any)
const MapSearchRoute = MapSearchRouteImport.update({
  id: '/map-search',
  path: '/map-search',
  getParentRoute: () => rootRouteImport,
} as any)
const MersinRoute = MersinRouteImport.update({
  id: '/mersin',
  path: '/mersin',
  getParentRoute: () => rootRouteImport,
} as any)
const OffPlanPropertyTurkeyRoute = OffPlanPropertyTurkeyRouteImport.update({
  id: '/off-plan-property-turkey',
  path: '/off-plan-property-turkey',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyForSaleInTurkeyRoute = PropertyForSaleInTurkeyRouteImport.update({
  id: '/property-for-sale-in-turkey',
  path: '/property-for-sale-in-turkey',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyGalleryRoute = PropertyGalleryRouteImport.update({
  id: '/property-gallery',
  path: '/property-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyWizardRoute = PropertyWizardRouteImport.update({
  id: '/property-wizard',
  path: '/property-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TurkishCitizenshipByInvestmentRoute =
  TurkishCitizenshipByInvestmentRouteImport.update({
    id: '/turkish-citizenship-by-investment',
    path: '/turkish-citizenship-by-investment',
    getParentRoute: () => rootRouteImport,
  } as any)
const WizardThankYouRoute = WizardThankYouRouteImport.update({
  id: '/wizard-thank-you',
  path: '/wizard-thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAboutUsRoute = LocaleAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAiPropertySearchRoute = LocaleAiPropertySearchRouteImport.update({
  id: '/ai-property-search',
  path: '/ai-property-search',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAliKaranRoute = LocaleAliKaranRouteImport.update({
  id: '/ali-karan',
  path: '/ali-karan',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAntalyaRoute = LocaleAntalyaRouteImport.update({
  id: '/antalya',
  path: '/antalya',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleApartmentsForSaleInTurkeyRoute =
  LocaleApartmentsForSaleInTurkeyRouteImport.update({
    id: '/apartments-for-sale-in-turkey',
    path: '/apartments-for-sale-in-turkey',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleBaliRoute = LocaleBaliRouteImport.update({
  id: '/bali',
  path: '/bali',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleContactThankYouRoute = LocaleContactThankYouRouteImport.update({
  id: '/contact-thank-you',
  path: '/contact-thank-you',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleContactUsRoute = LocaleContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCyprusRoute = LocaleCyprusRouteImport.update({
  id: '/cyprus',
  path: '/cyprus',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDesignYourHomeRoute = LocaleDesignYourHomeRouteImport.update({
  id: '/design-your-home',
  path: '/design-your-home',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDubaiRoute = LocaleDubaiRouteImport.update({
  id: '/dubai',
  path: '/dubai',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleInformationRoute = LocaleInformationRouteImport.update({
  id: '/information',
  path: '/information',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleIstanbulRoute = LocaleIstanbulRouteImport.update({
  id: '/istanbul',
  path: '/istanbul',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleLuxuryVillasInTurkeyRoute =
  LocaleLuxuryVillasInTurkeyRouteImport.update({
    id: '/luxury-villas-in-turkey',
    path: '/luxury-villas-in-turkey',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleMapSearchRoute = LocaleMapSearchRouteImport.update({
  id: '/map-search',
  path: '/map-search',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleMersinRoute = LocaleMersinRouteImport.update({
  id: '/mersin',
  path: '/mersin',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleOffPlanPropertyTurkeyRoute =
  LocaleOffPlanPropertyTurkeyRouteImport.update({
    id: '/off-plan-property-turkey',
    path: '/off-plan-property-turkey',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleOurStoryRoute = LocaleOurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePropertyForSaleInTurkeyRoute =
  LocalePropertyForSaleInTurkeyRouteImport.update({
    id: '/property-for-sale-in-turkey',
    path: '/property-for-sale-in-turkey',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocalePropertyGalleryRoute = LocalePropertyGalleryRouteImport.update({
  id: '/property-gallery',
  path: '/property-gallery',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePropertyWizardRoute = LocalePropertyWizardRouteImport.update({
  id: '/property-wizard',
  path: '/property-wizard',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleTestimonialsRoute = LocaleTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleTurkishCitizenshipByInvestmentRoute =
  LocaleTurkishCitizenshipByInvestmentRouteImport.update({
    id: '/turkish-citizenship-by-investment',
    path: '/turkish-citizenship-by-investment',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleWizardThankYouRoute = LocaleWizardThankYouRouteImport.update({
  id: '/wizard-thank-you',
  path: '/wizard-thank-you',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const SegmentIdRoute = SegmentIdRouteImport.update({
  id: '/$segment/$id',
  path: '/$segment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAiInsightsRoute = AdminAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSocialListeningRoute = AdminSocialListeningRouteImport.update({
  id: '/social-listening',
  path: '/social-listening',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesExpensesBuyingPropertyTurkeyRoute =
  ArticlesExpensesBuyingPropertyTurkeyRouteImport.update({
    id: '/articles/expenses-buying-property-turkey',
    path: '/articles/expenses-buying-property-turkey',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSegmentIdRoute = LocaleSegmentIdRouteImport.update({
  id: '/$segment/$id',
  path: '/$segment/$id',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleArticleIdRoute = LocaleArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleArticlesSlugRoute = LocaleArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleArticlesExpensesBuyingPropertyTurkeyRoute =
  LocaleArticlesExpensesBuyingPropertyTurkeyRouteImport.update({
    id: '/articles/expenses-buying-property-turkey',
    path: '/articles/expenses-buying-property-turkey',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleCoursesIndexRoute = LocaleCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsEmailRoute = AdminAnalyticsEmailRouteImport.update({
  id: '/analytics/email',
  path: '/analytics/email',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsHeatmapRoute = AdminAnalyticsHeatmapRouteImport.update({
  id: '/analytics/heatmap',
  path: '/analytics/heatmap',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsLeadsRoute = AdminAnalyticsLeadsRouteImport.update({
  id: '/analytics/leads',
  path: '/analytics/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsPropertiesRoute =
  AdminAnalyticsPropertiesRouteImport.update({
    id: '/analytics/properties',
    path: '/analytics/properties',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAnalyticsRealtimeRoute = AdminAnalyticsRealtimeRouteImport.update({
  id: '/analytics/realtime',
  path: '/analytics/realtime',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsTrafficRoute = AdminAnalyticsTrafficRouteImport.update({
  id: '/analytics/traffic',
  path: '/analytics/traffic',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogAiRoute = AdminBlogAiRouteImport.update({
  id: '/blog/ai',
  path: '/blog/ai',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCrmIndexRoute = AdminCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCrmContactsRoute = AdminCrmContactsRouteImport.update({
  id: '/crm/contacts',
  path: '/crm/contacts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCrmTasksRoute = AdminCrmTasksRouteImport.update({
  id: '/crm/tasks',
  path: '/crm/tasks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailIndexRoute = AdminEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailInboxRoute = AdminEmailInboxRouteImport.update({
  id: '/email/inbox',
  path: '/email/inbox',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailSubscribersRoute = AdminEmailSubscribersRouteImport.update({
  id: '/email/subscribers',
  path: '/email/subscribers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email/templates',
  path: '/email/templates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOfficeDocumentsRoute = AdminOfficeDocumentsRouteImport.update({
  id: '/office/documents',
  path: '/office/documents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOfficeSpreadsheetRoute = AdminOfficeSpreadsheetRouteImport.update({
  id: '/office/spreadsheet',
  path: '/office/spreadsheet',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPresentationsIndexRoute = AdminPresentationsIndexRouteImport.update({
  id: '/presentations/',
  path: '/presentations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPresentationsIdRoute = AdminPresentationsIdRouteImport.update({
  id: '/presentations/$id',
  path: '/presentations/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPropertiesIndexRoute = AdminPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPropertiesNewRoute = AdminPropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CoursesCountryIndexRoute = CoursesCountryIndexRouteImport.update({
  id: '/courses/$country/',
  path: '/courses/$country/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCountryModuleSlugRoute =
  CoursesCountryModuleSlugRouteImport.update({
    id: '/courses/$country/$moduleSlug',
    path: '/courses/$country/$moduleSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCountryFinalExamRoute = CoursesCountryFinalExamRouteImport.update({
  id: '/courses/$country/final-exam',
  path: '/courses/$country/final-exam',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCoursesCountryIndexRoute =
  LocaleCoursesCountryIndexRouteImport.update({
    id: '/courses/$country/',
    path: '/courses/$country/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleCoursesCountryModuleSlugRoute =
  LocaleCoursesCountryModuleSlugRouteImport.update({
    id: '/courses/$country/$moduleSlug',
    path: '/courses/$country/$moduleSlug',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleCoursesCountryFinalExamRoute =
  LocaleCoursesCountryFinalExamRouteImport.update({
    id: '/courses/$country/final-exam',
    path: '/courses/$country/final-exam',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const AdminCrmLeadsIndexRoute = AdminCrmLeadsIndexRouteImport.update({
  id: '/crm/leads/',
  path: '/crm/leads/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCrmLeadsIdRoute = AdminCrmLeadsIdRouteImport.update({
  id: '/crm/leads/$id',
  path: '/crm/leads/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailCampaignsIndexRoute =
  AdminEmailCampaignsIndexRouteImport.update({
    id: '/email/campaigns/',
    path: '/email/campaigns/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminEmailCampaignsIdRoute = AdminEmailCampaignsIdRouteImport.update({
  id: '/email/campaigns/$id',
  path: '/email/campaigns/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailCampaignsNewRoute = AdminEmailCampaignsNewRouteImport.update({
  id: '/email/campaigns/new',
  path: '/email/campaigns/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPropertiesIdIndexRoute = AdminPropertiesIdIndexRouteImport.update({
  id: '/properties/$id/',
  path: '/properties/$id/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPropertiesIdEditRoute = AdminPropertiesIdEditRouteImport.update({
  id: '/properties/$id/edit',
  path: '/properties/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-property-search': typeof AiPropertySearchRoute
  '/ali-karan': typeof AliKaranRoute
  '/antalya': typeof AntalyaRoute
  '/apartments-for-sale-in-turkey': typeof ApartmentsForSaleInTurkeyRoute
  '/bali': typeof BaliRoute
  '/contact-thank-you': typeof ContactThankYouRoute
  '/contact-us': typeof ContactUsRoute
  '/cyprus': typeof CyprusRoute
  '/design-your-home': typeof DesignYourHomeRoute
  '/dubai': typeof DubaiRoute
  '/information': typeof InformationRoute
  '/istanbul': typeof IstanbulRoute
  '/luxury-villas-in-turkey': typeof LuxuryVillasInTurkeyRoute
  '/map-search': typeof MapSearchRoute
  '/mersin': typeof MersinRoute
  '/off-plan-property-turkey': typeof OffPlanPropertyTurkeyRoute
  '/our-story': typeof OurStoryRoute
  '/property-for-sale-in-turkey': typeof PropertyForSaleInTurkeyRoute
  '/property-gallery': typeof PropertyGalleryRoute
  '/property-wizard': typeof PropertyWizardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/turkish-citizenship-by-investment': typeof TurkishCitizenshipByInvestmentRoute
  '/wizard-thank-you': typeof WizardThankYouRoute
  '/$locale/about-us': typeof LocaleAboutUsRoute
  '/$locale/ai-property-search': typeof LocaleAiPropertySearchRoute
  '/$locale/ali-karan': typeof LocaleAliKaranRoute
  '/$locale/antalya': typeof LocaleAntalyaRoute
  '/$locale/apartments-for-sale-in-turkey': typeof LocaleApartmentsForSaleInTurkeyRoute
  '/$locale/bali': typeof LocaleBaliRoute
  '/$locale/contact-thank-you': typeof LocaleContactThankYouRoute
  '/$locale/contact-us': typeof LocaleContactUsRoute
  '/$locale/cyprus': typeof LocaleCyprusRoute
  '/$locale/design-your-home': typeof LocaleDesignYourHomeRoute
  '/$locale/dubai': typeof LocaleDubaiRoute
  '/$locale/information': typeof LocaleInformationRoute
  '/$locale/istanbul': typeof LocaleIstanbulRoute
  '/$locale/luxury-villas-in-turkey': typeof LocaleLuxuryVillasInTurkeyRoute
  '/$locale/map-search': typeof LocaleMapSearchRoute
  '/$locale/mersin': typeof LocaleMersinRoute
  '/$locale/off-plan-property-turkey': typeof LocaleOffPlanPropertyTurkeyRoute
  '/$locale/our-story': typeof LocaleOurStoryRoute
  '/$locale/property-for-sale-in-turkey': typeof LocalePropertyForSaleInTurkeyRoute
  '/$locale/property-gallery': typeof LocalePropertyGalleryRoute
  '/$locale/property-wizard': typeof LocalePropertyWizardRoute
  '/$locale/testimonials': typeof LocaleTestimonialsRoute
  '/$locale/turkish-citizenship-by-investment': typeof LocaleTurkishCitizenshipByInvestmentRoute
  '/$locale/wizard-thank-you': typeof LocaleWizardThankYouRoute
  '/$segment/$id': typeof SegmentIdRoute
  '/admin/ai-insights': typeof AdminAiInsightsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social-listening': typeof AdminSocialListeningRoute
  '/article/$id': typeof ArticleIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/expenses-buying-property-turkey': typeof ArticlesExpensesBuyingPropertyTurkeyRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/$locale/$segment/$id': typeof LocaleSegmentIdRoute
  '/$locale/article/$id': typeof LocaleArticleIdRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/articles/expenses-buying-property-turkey': typeof LocaleArticlesExpensesBuyingPropertyTurkeyRoute
  '/admin/analytics/email': typeof AdminAnalyticsEmailRoute
  '/admin/analytics/heatmap': typeof AdminAnalyticsHeatmapRoute
  '/admin/analytics/leads': typeof AdminAnalyticsLeadsRoute
  '/admin/analytics/properties': typeof AdminAnalyticsPropertiesRoute
  '/admin/analytics/realtime': typeof AdminAnalyticsRealtimeRoute
  '/admin/analytics/traffic': typeof AdminAnalyticsTrafficRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/ai': typeof AdminBlogAiRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/crm/contacts': typeof AdminCrmContactsRoute
  '/admin/crm/tasks': typeof AdminCrmTasksRoute
  '/admin/email/inbox': typeof AdminEmailInboxRoute
  '/admin/email/subscribers': typeof AdminEmailSubscribersRoute
  '/admin/email/templates': typeof AdminEmailTemplatesRoute
  '/admin/office/documents': typeof AdminOfficeDocumentsRoute
  '/admin/office/spreadsheet': typeof AdminOfficeSpreadsheetRoute
  '/admin/presentations/$id': typeof AdminPresentationsIdRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/courses/$country/$moduleSlug': typeof CoursesCountryModuleSlugRoute
  '/courses/$country/final-exam': typeof CoursesCountryFinalExamRoute
  '/$locale/courses/': typeof LocaleCoursesIndexRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/crm/': typeof AdminCrmIndexRoute
  '/admin/email/': typeof AdminEmailIndexRoute
  '/admin/presentations/': typeof AdminPresentationsIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/courses/$country/': typeof CoursesCountryIndexRoute
  '/$locale/courses/$country/$moduleSlug': typeof LocaleCoursesCountryModuleSlugRoute
  '/$locale/courses/$country/final-exam': typeof LocaleCoursesCountryFinalExamRoute
  '/admin/crm/leads/$id': typeof AdminCrmLeadsIdRoute
  '/admin/email/campaigns/$id': typeof AdminEmailCampaignsIdRoute
  '/admin/email/campaigns/new': typeof AdminEmailCampaignsNewRoute
  '/admin/properties/$id/edit': typeof AdminPropertiesIdEditRoute
  '/$locale/courses/$country/': typeof LocaleCoursesCountryIndexRoute
  '/admin/crm/leads/': typeof AdminCrmLeadsIndexRoute
  '/admin/email/campaigns/': typeof AdminEmailCampaignsIndexRoute
  '/admin/properties/$id/': typeof AdminPropertiesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-property-search': typeof AiPropertySearchRoute
  '/ali-karan': typeof AliKaranRoute
  '/antalya': typeof AntalyaRoute
  '/apartments-for-sale-in-turkey': typeof ApartmentsForSaleInTurkeyRoute
  '/bali': typeof BaliRoute
  '/contact-thank-you': typeof ContactThankYouRoute
  '/contact-us': typeof ContactUsRoute
  '/cyprus': typeof CyprusRoute
  '/design-your-home': typeof DesignYourHomeRoute
  '/dubai': typeof DubaiRoute
  '/information': typeof InformationRoute
  '/istanbul': typeof IstanbulRoute
  '/luxury-villas-in-turkey': typeof LuxuryVillasInTurkeyRoute
  '/map-search': typeof MapSearchRoute
  '/mersin': typeof MersinRoute
  '/off-plan-property-turkey': typeof OffPlanPropertyTurkeyRoute
  '/our-story': typeof OurStoryRoute
  '/property-for-sale-in-turkey': typeof PropertyForSaleInTurkeyRoute
  '/property-gallery': typeof PropertyGalleryRoute
  '/property-wizard': typeof PropertyWizardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/turkish-citizenship-by-investment': typeof TurkishCitizenshipByInvestmentRoute
  '/wizard-thank-you': typeof WizardThankYouRoute
  '/$locale/about-us': typeof LocaleAboutUsRoute
  '/$locale/ai-property-search': typeof LocaleAiPropertySearchRoute
  '/$locale/ali-karan': typeof LocaleAliKaranRoute
  '/$locale/antalya': typeof LocaleAntalyaRoute
  '/$locale/apartments-for-sale-in-turkey': typeof LocaleApartmentsForSaleInTurkeyRoute
  '/$locale/bali': typeof LocaleBaliRoute
  '/$locale/contact-thank-you': typeof LocaleContactThankYouRoute
  '/$locale/contact-us': typeof LocaleContactUsRoute
  '/$locale/cyprus': typeof LocaleCyprusRoute
  '/$locale/design-your-home': typeof LocaleDesignYourHomeRoute
  '/$locale/dubai': typeof LocaleDubaiRoute
  '/$locale/information': typeof LocaleInformationRoute
  '/$locale/istanbul': typeof LocaleIstanbulRoute
  '/$locale/luxury-villas-in-turkey': typeof LocaleLuxuryVillasInTurkeyRoute
  '/$locale/map-search': typeof LocaleMapSearchRoute
  '/$locale/mersin': typeof LocaleMersinRoute
  '/$locale/off-plan-property-turkey': typeof LocaleOffPlanPropertyTurkeyRoute
  '/$locale/our-story': typeof LocaleOurStoryRoute
  '/$locale/property-for-sale-in-turkey': typeof LocalePropertyForSaleInTurkeyRoute
  '/$locale/property-gallery': typeof LocalePropertyGalleryRoute
  '/$locale/property-wizard': typeof LocalePropertyWizardRoute
  '/$locale/testimonials': typeof LocaleTestimonialsRoute
  '/$locale/turkish-citizenship-by-investment': typeof LocaleTurkishCitizenshipByInvestmentRoute
  '/$locale/wizard-thank-you': typeof LocaleWizardThankYouRoute
  '/$segment/$id': typeof SegmentIdRoute
  '/admin/ai-insights': typeof AdminAiInsightsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social-listening': typeof AdminSocialListeningRoute
  '/article/$id': typeof ArticleIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/expenses-buying-property-turkey': typeof ArticlesExpensesBuyingPropertyTurkeyRoute
  '/$locale': typeof LocaleIndexRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/$locale/$segment/$id': typeof LocaleSegmentIdRoute
  '/$locale/article/$id': typeof LocaleArticleIdRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/articles/expenses-buying-property-turkey': typeof LocaleArticlesExpensesBuyingPropertyTurkeyRoute
  '/admin/analytics/email': typeof AdminAnalyticsEmailRoute
  '/admin/analytics/heatmap': typeof AdminAnalyticsHeatmapRoute
  '/admin/analytics/leads': typeof AdminAnalyticsLeadsRoute
  '/admin/analytics/properties': typeof AdminAnalyticsPropertiesRoute
  '/admin/analytics/realtime': typeof AdminAnalyticsRealtimeRoute
  '/admin/analytics/traffic': typeof AdminAnalyticsTrafficRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/ai': typeof AdminBlogAiRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/crm/contacts': typeof AdminCrmContactsRoute
  '/admin/crm/tasks': typeof AdminCrmTasksRoute
  '/admin/email/inbox': typeof AdminEmailInboxRoute
  '/admin/email/subscribers': typeof AdminEmailSubscribersRoute
  '/admin/email/templates': typeof AdminEmailTemplatesRoute
  '/admin/office/documents': typeof AdminOfficeDocumentsRoute
  '/admin/office/spreadsheet': typeof AdminOfficeSpreadsheetRoute
  '/admin/presentations/$id': typeof AdminPresentationsIdRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/courses/$country/$moduleSlug': typeof CoursesCountryModuleSlugRoute
  '/courses/$country/final-exam': typeof CoursesCountryFinalExamRoute
  '/$locale/courses': typeof LocaleCoursesIndexRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/crm': typeof AdminCrmIndexRoute
  '/admin/email': typeof AdminEmailIndexRoute
  '/admin/presentations': typeof AdminPresentationsIndexRoute
  '/admin/properties': typeof AdminPropertiesIndexRoute
  '/courses/$country': typeof CoursesCountryIndexRoute
  '/$locale/courses/$country/$moduleSlug': typeof LocaleCoursesCountryModuleSlugRoute
  '/$locale/courses/$country/final-exam': typeof LocaleCoursesCountryFinalExamRoute
  '/admin/crm/leads/$id': typeof AdminCrmLeadsIdRoute
  '/admin/email/campaigns/$id': typeof AdminEmailCampaignsIdRoute
  '/admin/email/campaigns/new': typeof AdminEmailCampaignsNewRoute
  '/admin/properties/$id/edit': typeof AdminPropertiesIdEditRoute
  '/$locale/courses/$country': typeof LocaleCoursesCountryIndexRoute
  '/admin/crm/leads': typeof AdminCrmLeadsIndexRoute
  '/admin/email/campaigns': typeof AdminEmailCampaignsIndexRoute
  '/admin/properties/$id': typeof AdminPropertiesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-property-search': typeof AiPropertySearchRoute
  '/ali-karan': typeof AliKaranRoute
  '/antalya': typeof AntalyaRoute
  '/apartments-for-sale-in-turkey': typeof ApartmentsForSaleInTurkeyRoute
  '/bali': typeof BaliRoute
  '/contact-thank-you': typeof ContactThankYouRoute
  '/contact-us': typeof ContactUsRoute
  '/cyprus': typeof CyprusRoute
  '/design-your-home': typeof DesignYourHomeRoute
  '/dubai': typeof DubaiRoute
  '/information': typeof InformationRoute
  '/istanbul': typeof IstanbulRoute
  '/luxury-villas-in-turkey': typeof LuxuryVillasInTurkeyRoute
  '/map-search': typeof MapSearchRoute
  '/mersin': typeof MersinRoute
  '/off-plan-property-turkey': typeof OffPlanPropertyTurkeyRoute
  '/our-story': typeof OurStoryRoute
  '/property-for-sale-in-turkey': typeof PropertyForSaleInTurkeyRoute
  '/property-gallery': typeof PropertyGalleryRoute
  '/property-wizard': typeof PropertyWizardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/turkish-citizenship-by-investment': typeof TurkishCitizenshipByInvestmentRoute
  '/wizard-thank-you': typeof WizardThankYouRoute
  '/$locale/about-us': typeof LocaleAboutUsRoute
  '/$locale/ai-property-search': typeof LocaleAiPropertySearchRoute
  '/$locale/ali-karan': typeof LocaleAliKaranRoute
  '/$locale/antalya': typeof LocaleAntalyaRoute
  '/$locale/apartments-for-sale-in-turkey': typeof LocaleApartmentsForSaleInTurkeyRoute
  '/$locale/bali': typeof LocaleBaliRoute
  '/$locale/contact-thank-you': typeof LocaleContactThankYouRoute
  '/$locale/contact-us': typeof LocaleContactUsRoute
  '/$locale/cyprus': typeof LocaleCyprusRoute
  '/$locale/design-your-home': typeof LocaleDesignYourHomeRoute
  '/$locale/dubai': typeof LocaleDubaiRoute
  '/$locale/information': typeof LocaleInformationRoute
  '/$locale/istanbul': typeof LocaleIstanbulRoute
  '/$locale/luxury-villas-in-turkey': typeof LocaleLuxuryVillasInTurkeyRoute
  '/$locale/map-search': typeof LocaleMapSearchRoute
  '/$locale/mersin': typeof LocaleMersinRoute
  '/$locale/off-plan-property-turkey': typeof LocaleOffPlanPropertyTurkeyRoute
  '/$locale/our-story': typeof LocaleOurStoryRoute
  '/$locale/property-for-sale-in-turkey': typeof LocalePropertyForSaleInTurkeyRoute
  '/$locale/property-gallery': typeof LocalePropertyGalleryRoute
  '/$locale/property-wizard': typeof LocalePropertyWizardRoute
  '/$locale/testimonials': typeof LocaleTestimonialsRoute
  '/$locale/turkish-citizenship-by-investment': typeof LocaleTurkishCitizenshipByInvestmentRoute
  '/$locale/wizard-thank-you': typeof LocaleWizardThankYouRoute
  '/$segment/$id': typeof SegmentIdRoute
  '/admin/ai-insights': typeof AdminAiInsightsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social-listening': typeof AdminSocialListeningRoute
  '/article/$id': typeof ArticleIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/expenses-buying-property-turkey': typeof ArticlesExpensesBuyingPropertyTurkeyRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/$locale/$segment/$id': typeof LocaleSegmentIdRoute
  '/$locale/article/$id': typeof LocaleArticleIdRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/articles/expenses-buying-property-turkey': typeof LocaleArticlesExpensesBuyingPropertyTurkeyRoute
  '/admin/analytics/email': typeof AdminAnalyticsEmailRoute
  '/admin/analytics/heatmap': typeof AdminAnalyticsHeatmapRoute
  '/admin/analytics/leads': typeof AdminAnalyticsLeadsRoute
  '/admin/analytics/properties': typeof AdminAnalyticsPropertiesRoute
  '/admin/analytics/realtime': typeof AdminAnalyticsRealtimeRoute
  '/admin/analytics/traffic': typeof AdminAnalyticsTrafficRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/ai': typeof AdminBlogAiRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/crm/contacts': typeof AdminCrmContactsRoute
  '/admin/crm/tasks': typeof AdminCrmTasksRoute
  '/admin/email/inbox': typeof AdminEmailInboxRoute
  '/admin/email/subscribers': typeof AdminEmailSubscribersRoute
  '/admin/email/templates': typeof AdminEmailTemplatesRoute
  '/admin/office/documents': typeof AdminOfficeDocumentsRoute
  '/admin/office/spreadsheet': typeof AdminOfficeSpreadsheetRoute
  '/admin/presentations/$id': typeof AdminPresentationsIdRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/courses/$country/$moduleSlug': typeof CoursesCountryModuleSlugRoute
  '/courses/$country/final-exam': typeof CoursesCountryFinalExamRoute
  '/$locale/courses/': typeof LocaleCoursesIndexRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/crm/': typeof AdminCrmIndexRoute
  '/admin/email/': typeof AdminEmailIndexRoute
  '/admin/presentations/': typeof AdminPresentationsIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/courses/$country/': typeof CoursesCountryIndexRoute
  '/$locale/courses/$country/$moduleSlug': typeof LocaleCoursesCountryModuleSlugRoute
  '/$locale/courses/$country/final-exam': typeof LocaleCoursesCountryFinalExamRoute
  '/admin/crm/leads/$id': typeof AdminCrmLeadsIdRoute
  '/admin/email/campaigns/$id': typeof AdminEmailCampaignsIdRoute
  '/admin/email/campaigns/new': typeof AdminEmailCampaignsNewRoute
  '/admin/properties/$id/edit': typeof AdminPropertiesIdEditRoute
  '/$locale/courses/$country/': typeof LocaleCoursesCountryIndexRoute
  '/admin/crm/leads/': typeof AdminCrmLeadsIndexRoute
  '/admin/email/campaigns/': typeof AdminEmailCampaignsIndexRoute
  '/admin/properties/$id/': typeof AdminPropertiesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/$'
    | '/$slug'
    | '/about-us'
    | '/admin-dashboard'
    | '/admin-login'
    | '/ai-property-search'
    | '/ali-karan'
    | '/antalya'
    | '/apartments-for-sale-in-turkey'
    | '/bali'
    | '/contact-thank-you'
    | '/contact-us'
    | '/cyprus'
    | '/design-your-home'
    | '/dubai'
    | '/information'
    | '/istanbul'
    | '/luxury-villas-in-turkey'
    | '/map-search'
    | '/mersin'
    | '/off-plan-property-turkey'
    | '/our-story'
    | '/property-for-sale-in-turkey'
    | '/property-gallery'
    | '/property-wizard'
    | '/sitemap.xml'
    | '/testimonials'
    | '/turkish-citizenship-by-investment'
    | '/wizard-thank-you'
    | '/$locale/about-us'
    | '/$locale/ai-property-search'
    | '/$locale/ali-karan'
    | '/$locale/antalya'
    | '/$locale/apartments-for-sale-in-turkey'
    | '/$locale/bali'
    | '/$locale/contact-thank-you'
    | '/$locale/contact-us'
    | '/$locale/cyprus'
    | '/$locale/design-your-home'
    | '/$locale/dubai'
    | '/$locale/information'
    | '/$locale/istanbul'
    | '/$locale/luxury-villas-in-turkey'
    | '/$locale/map-search'
    | '/$locale/mersin'
    | '/$locale/off-plan-property-turkey'
    | '/$locale/our-story'
    | '/$locale/property-for-sale-in-turkey'
    | '/$locale/property-gallery'
    | '/$locale/property-wizard'
    | '/$locale/testimonials'
    | '/$locale/turkish-citizenship-by-investment'
    | '/$locale/wizard-thank-you'
    | '/$segment/$id'
    | '/admin/ai-insights'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/social-listening'
    | '/article/$id'
    | '/articles/$slug'
    | '/articles/expenses-buying-property-turkey'
    | '/$locale/'
    | '/admin/'
    | '/courses/'
    | '/$locale/$segment/$id'
    | '/$locale/article/$id'
    | '/$locale/articles/$slug'
    | '/$locale/articles/expenses-buying-property-turkey'
    | '/admin/analytics/email'
    | '/admin/analytics/heatmap'
    | '/admin/analytics/leads'
    | '/admin/analytics/properties'
    | '/admin/analytics/realtime'
    | '/admin/analytics/traffic'
    | '/admin/blog/$id'
    | '/admin/blog/ai'
    | '/admin/blog/new'
    | '/admin/crm/contacts'
    | '/admin/crm/tasks'
    | '/admin/email/inbox'
    | '/admin/email/subscribers'
    | '/admin/email/templates'
    | '/admin/office/documents'
    | '/admin/office/spreadsheet'
    | '/admin/presentations/$id'
    | '/admin/properties/new'
    | '/courses/$country/$moduleSlug'
    | '/courses/$country/final-exam'
    | '/$locale/courses/'
    | '/admin/analytics/'
    | '/admin/blog/'
    | '/admin/crm/'
    | '/admin/email/'
    | '/admin/presentations/'
    | '/admin/properties/'
    | '/courses/$country/'
    | '/$locale/courses/$country/$moduleSlug'
    | '/$locale/courses/$country/final-exam'
    | '/admin/crm/leads/$id'
    | '/admin/email/campaigns/$id'
    | '/admin/email/campaigns/new'
    | '/admin/properties/$id/edit'
    | '/$locale/courses/$country/'
    | '/admin/crm/leads/'
    | '/admin/email/campaigns/'
    | '/admin/properties/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$slug'
    | '/about-us'
    | '/admin-dashboard'
    | '/admin-login'
    | '/ai-property-search'
    | '/ali-karan'
    | '/antalya'
    | '/apartments-for-sale-in-turkey'
    | '/bali'
    | '/contact-thank-you'
    | '/contact-us'
    | '/cyprus'
    | '/design-your-home'
    | '/dubai'
    | '/information'
    | '/istanbul'
    | '/luxury-villas-in-turkey'
    | '/map-search'
    | '/mersin'
    | '/off-plan-property-turkey'
    | '/our-story'
    | '/property-for-sale-in-turkey'
    | '/property-gallery'
    | '/property-wizard'
    | '/sitemap.xml'
    | '/testimonials'
    | '/turkish-citizenship-by-investment'
    | '/wizard-thank-you'
    | '/$locale/about-us'
    | '/$locale/ai-property-search'
    | '/$locale/ali-karan'
    | '/$locale/antalya'
    | '/$locale/apartments-for-sale-in-turkey'
    | '/$locale/bali'
    | '/$locale/contact-thank-you'
    | '/$locale/contact-us'
    | '/$locale/cyprus'
    | '/$locale/design-your-home'
    | '/$locale/dubai'
    | '/$locale/information'
    | '/$locale/istanbul'
    | '/$locale/luxury-villas-in-turkey'
    | '/$locale/map-search'
    | '/$locale/mersin'
    | '/$locale/off-plan-property-turkey'
    | '/$locale/our-story'
    | '/$locale/property-for-sale-in-turkey'
    | '/$locale/property-gallery'
    | '/$locale/property-wizard'
    | '/$locale/testimonials'
    | '/$locale/turkish-citizenship-by-investment'
    | '/$locale/wizard-thank-you'
    | '/$segment/$id'
    | '/admin/ai-insights'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/social-listening'
    | '/article/$id'
    | '/articles/$slug'
    | '/articles/expenses-buying-property-turkey'
    | '/$locale'
    | '/admin'
    | '/courses'
    | '/$locale/$segment/$id'
    | '/$locale/article/$id'
    | '/$locale/articles/$slug'
    | '/$locale/articles/expenses-buying-property-turkey'
    | '/admin/analytics/email'
    | '/admin/analytics/heatmap'
    | '/admin/analytics/leads'
    | '/admin/analytics/properties'
    | '/admin/analytics/realtime'
    | '/admin/analytics/traffic'
    | '/admin/blog/$id'
    | '/admin/blog/ai'
    | '/admin/blog/new'
    | '/admin/crm/contacts'
    | '/admin/crm/tasks'
    | '/admin/email/inbox'
    | '/admin/email/subscribers'
    | '/admin/email/templates'
    | '/admin/office/documents'
    | '/admin/office/spreadsheet'
    | '/admin/presentations/$id'
    | '/admin/properties/new'
    | '/courses/$country/$moduleSlug'
    | '/courses/$country/final-exam'
    | '/$locale/courses'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/crm'
    | '/admin/email'
    | '/admin/presentations'
    | '/admin/properties'
    | '/courses/$country'
    | '/$locale/courses/$country/$moduleSlug'
    | '/$locale/courses/$country/final-exam'
    | '/admin/crm/leads/$id'
    | '/admin/email/campaigns/$id'
    | '/admin/email/campaigns/new'
    | '/admin/properties/$id/edit'
    | '/$locale/courses/$country'
    | '/admin/crm/leads'
    | '/admin/email/campaigns'
    | '/admin/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/$'
    | '/$slug'
    | '/about-us'
    | '/admin-dashboard'
    | '/admin-login'
    | '/ai-property-search'
    | '/ali-karan'
    | '/antalya'
    | '/apartments-for-sale-in-turkey'
    | '/bali'
    | '/contact-thank-you'
    | '/contact-us'
    | '/cyprus'
    | '/design-your-home'
    | '/dubai'
    | '/information'
    | '/istanbul'
    | '/luxury-villas-in-turkey'
    | '/map-search'
    | '/mersin'
    | '/off-plan-property-turkey'
    | '/our-story'
    | '/property-for-sale-in-turkey'
    | '/property-gallery'
    | '/property-wizard'
    | '/sitemap.xml'
    | '/testimonials'
    | '/turkish-citizenship-by-investment'
    | '/wizard-thank-you'
    | '/$locale/about-us'
    | '/$locale/ai-property-search'
    | '/$locale/ali-karan'
    | '/$locale/antalya'
    | '/$locale/apartments-for-sale-in-turkey'
    | '/$locale/bali'
    | '/$locale/contact-thank-you'
    | '/$locale/contact-us'
    | '/$locale/cyprus'
    | '/$locale/design-your-home'
    | '/$locale/dubai'
    | '/$locale/information'
    | '/$locale/istanbul'
    | '/$locale/luxury-villas-in-turkey'
    | '/$locale/map-search'
    | '/$locale/mersin'
    | '/$locale/off-plan-property-turkey'
    | '/$locale/our-story'
    | '/$locale/property-for-sale-in-turkey'
    | '/$locale/property-gallery'
    | '/$locale/property-wizard'
    | '/$locale/testimonials'
    | '/$locale/turkish-citizenship-by-investment'
    | '/$locale/wizard-thank-you'
    | '/$segment/$id'
    | '/admin/ai-insights'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/social-listening'
    | '/article/$id'
    | '/articles/$slug'
    | '/articles/expenses-buying-property-turkey'
    | '/$locale/'
    | '/admin/'
    | '/courses/'
    | '/$locale/$segment/$id'
    | '/$locale/article/$id'
    | '/$locale/articles/$slug'
    | '/$locale/articles/expenses-buying-property-turkey'
    | '/admin/analytics/email'
    | '/admin/analytics/heatmap'
    | '/admin/analytics/leads'
    | '/admin/analytics/properties'
    | '/admin/analytics/realtime'
    | '/admin/analytics/traffic'
    | '/admin/blog/$id'
    | '/admin/blog/ai'
    | '/admin/blog/new'
    | '/admin/crm/contacts'
    | '/admin/crm/tasks'
    | '/admin/email/inbox'
    | '/admin/email/subscribers'
    | '/admin/email/templates'
    | '/admin/office/documents'
    | '/admin/office/spreadsheet'
    | '/admin/presentations/$id'
    | '/admin/properties/new'
    | '/courses/$country/$moduleSlug'
    | '/courses/$country/final-exam'
    | '/$locale/courses/'
    | '/admin/analytics/'
    | '/admin/blog/'
    | '/admin/crm/'
    | '/admin/email/'
    | '/admin/presentations/'
    | '/admin/properties/'
    | '/courses/$country/'
    | '/$locale/courses/$country/$moduleSlug'
    | '/$locale/courses/$country/final-exam'
    | '/admin/crm/leads/$id'
    | '/admin/email/campaigns/$id'
    | '/admin/email/campaigns/new'
    | '/admin/properties/$id/edit'
    | '/$locale/courses/$country/'
    | '/admin/crm/leads/'
    | '/admin/email/campaigns/'
    | '/admin/properties/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  SlugRoute: typeof SlugRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AiPropertySearchRoute: typeof AiPropertySearchRoute
  AliKaranRoute: typeof AliKaranRoute
  AntalyaRoute: typeof AntalyaRoute
  ApartmentsForSaleInTurkeyRoute: typeof ApartmentsForSaleInTurkeyRoute
  BaliRoute: typeof BaliRoute
  ContactThankYouRoute: typeof ContactThankYouRoute
  ContactUsRoute: typeof ContactUsRoute
  CyprusRoute: typeof CyprusRoute
  DesignYourHomeRoute: typeof DesignYourHomeRoute
  DubaiRoute: typeof DubaiRoute
  InformationRoute: typeof InformationRoute
  IstanbulRoute: typeof IstanbulRoute
  LuxuryVillasInTurkeyRoute: typeof LuxuryVillasInTurkeyRoute
  MapSearchRoute: typeof MapSearchRoute
  MersinRoute: typeof MersinRoute
  OffPlanPropertyTurkeyRoute: typeof OffPlanPropertyTurkeyRoute
  OurStoryRoute: typeof OurStoryRoute
  PropertyForSaleInTurkeyRoute: typeof PropertyForSaleInTurkeyRoute
  PropertyGalleryRoute: typeof PropertyGalleryRoute
  PropertyWizardRoute: typeof PropertyWizardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TurkishCitizenshipByInvestmentRoute: typeof TurkishCitizenshipByInvestmentRoute
  WizardThankYouRoute: typeof WizardThankYouRoute
  SegmentIdRoute: typeof SegmentIdRoute
  ArticleIdRoute: typeof ArticleIdRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesExpensesBuyingPropertyTurkeyRoute: typeof ArticlesExpensesBuyingPropertyTurkeyRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesCountryModuleSlugRoute: typeof CoursesCountryModuleSlugRoute
  CoursesCountryFinalExamRoute: typeof CoursesCountryFinalExamRoute
  CoursesCountryIndexRoute: typeof CoursesCountryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-property-search': {
      id: '/ai-property-search'
      path: '/ai-property-search'
      fullPath: '/ai-property-search'
      preLoaderRoute: typeof AiPropertySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ali-karan': {
      id: '/ali-karan'
      path: '/ali-karan'
      fullPath: '/ali-karan'
      preLoaderRoute: typeof AliKaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antalya': {
      id: '/antalya'
      path: '/antalya'
      fullPath: '/antalya'
      preLoaderRoute: typeof AntalyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments-for-sale-in-turkey': {
      id: '/apartments-for-sale-in-turkey'
      path: '/apartments-for-sale-in-turkey'
      fullPath: '/apartments-for-sale-in-turkey'
      preLoaderRoute: typeof ApartmentsForSaleInTurkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bali': {
      id: '/bali'
      path: '/bali'
      fullPath: '/bali'
      preLoaderRoute: typeof BaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-thank-you': {
      id: '/contact-thank-you'
      path: '/contact-thank-you'
      fullPath: '/contact-thank-you'
      preLoaderRoute: typeof ContactThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyprus': {
      id: '/cyprus'
      path: '/cyprus'
      fullPath: '/cyprus'
      preLoaderRoute: typeof CyprusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-your-home': {
      id: '/design-your-home'
      path: '/design-your-home'
      fullPath: '/design-your-home'
      preLoaderRoute: typeof DesignYourHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dubai': {
      id: '/dubai'
      path: '/dubai'
      fullPath: '/dubai'
      preLoaderRoute: typeof DubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information': {
      id: '/information'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/istanbul': {
      id: '/istanbul'
      path: '/istanbul'
      fullPath: '/istanbul'
      preLoaderRoute: typeof IstanbulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-villas-in-turkey': {
      id: '/luxury-villas-in-turkey'
      path: '/luxury-villas-in-turkey'
      fullPath: '/luxury-villas-in-turkey'
      preLoaderRoute: typeof LuxuryVillasInTurkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-search': {
      id: '/map-search'
      path: '/map-search'
      fullPath: '/map-search'
      preLoaderRoute: typeof MapSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mersin': {
      id: '/mersin'
      path: '/mersin'
      fullPath: '/mersin'
      preLoaderRoute: typeof MersinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/off-plan-property-turkey': {
      id: '/off-plan-property-turkey'
      path: '/off-plan-property-turkey'
      fullPath: '/off-plan-property-turkey'
      preLoaderRoute: typeof OffPlanPropertyTurkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-for-sale-in-turkey': {
      id: '/property-for-sale-in-turkey'
      path: '/property-for-sale-in-turkey'
      fullPath: '/property-for-sale-in-turkey'
      preLoaderRoute: typeof PropertyForSaleInTurkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-gallery': {
      id: '/property-gallery'
      path: '/property-gallery'
      fullPath: '/property-gallery'
      preLoaderRoute: typeof PropertyGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-wizard': {
      id: '/property-wizard'
      path: '/property-wizard'
      fullPath: '/property-wizard'
      preLoaderRoute: typeof PropertyWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turkish-citizenship-by-investment': {
      id: '/turkish-citizenship-by-investment'
      path: '/turkish-citizenship-by-investment'
      fullPath: '/turkish-citizenship-by-investment'
      preLoaderRoute: typeof TurkishCitizenshipByInvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard-thank-you': {
      id: '/wizard-thank-you'
      path: '/wizard-thank-you'
      fullPath: '/wizard-thank-you'
      preLoaderRoute: typeof WizardThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/about-us': {
      id: '/$locale/about-us'
      path: '/about-us'
      fullPath: '/$locale/about-us'
      preLoaderRoute: typeof LocaleAboutUsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/ai-property-search': {
      id: '/$locale/ai-property-search'
      path: '/ai-property-search'
      fullPath: '/$locale/ai-property-search'
      preLoaderRoute: typeof LocaleAiPropertySearchRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/ali-karan': {
      id: '/$locale/ali-karan'
      path: '/ali-karan'
      fullPath: '/$locale/ali-karan'
      preLoaderRoute: typeof LocaleAliKaranRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/antalya': {
      id: '/$locale/antalya'
      path: '/antalya'
      fullPath: '/$locale/antalya'
      preLoaderRoute: typeof LocaleAntalyaRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/apartments-for-sale-in-turkey': {
      id: '/$locale/apartments-for-sale-in-turkey'
      path: '/apartments-for-sale-in-turkey'
      fullPath: '/$locale/apartments-for-sale-in-turkey'
      preLoaderRoute: typeof LocaleApartmentsForSaleInTurkeyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/bali': {
      id: '/$locale/bali'
      path: '/bali'
      fullPath: '/$locale/bali'
      preLoaderRoute: typeof LocaleBaliRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/contact-thank-you': {
      id: '/$locale/contact-thank-you'
      path: '/contact-thank-you'
      fullPath: '/$locale/contact-thank-you'
      preLoaderRoute: typeof LocaleContactThankYouRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/contact-us': {
      id: '/$locale/contact-us'
      path: '/contact-us'
      fullPath: '/$locale/contact-us'
      preLoaderRoute: typeof LocaleContactUsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/cyprus': {
      id: '/$locale/cyprus'
      path: '/cyprus'
      fullPath: '/$locale/cyprus'
      preLoaderRoute: typeof LocaleCyprusRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/design-your-home': {
      id: '/$locale/design-your-home'
      path: '/design-your-home'
      fullPath: '/$locale/design-your-home'
      preLoaderRoute: typeof LocaleDesignYourHomeRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/dubai': {
      id: '/$locale/dubai'
      path: '/dubai'
      fullPath: '/$locale/dubai'
      preLoaderRoute: typeof LocaleDubaiRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/information': {
      id: '/$locale/information'
      path: '/information'
      fullPath: '/$locale/information'
      preLoaderRoute: typeof LocaleInformationRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/istanbul': {
      id: '/$locale/istanbul'
      path: '/istanbul'
      fullPath: '/$locale/istanbul'
      preLoaderRoute: typeof LocaleIstanbulRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/luxury-villas-in-turkey': {
      id: '/$locale/luxury-villas-in-turkey'
      path: '/luxury-villas-in-turkey'
      fullPath: '/$locale/luxury-villas-in-turkey'
      preLoaderRoute: typeof LocaleLuxuryVillasInTurkeyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/map-search': {
      id: '/$locale/map-search'
      path: '/map-search'
      fullPath: '/$locale/map-search'
      preLoaderRoute: typeof LocaleMapSearchRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/mersin': {
      id: '/$locale/mersin'
      path: '/mersin'
      fullPath: '/$locale/mersin'
      preLoaderRoute: typeof LocaleMersinRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/off-plan-property-turkey': {
      id: '/$locale/off-plan-property-turkey'
      path: '/off-plan-property-turkey'
      fullPath: '/$locale/off-plan-property-turkey'
      preLoaderRoute: typeof LocaleOffPlanPropertyTurkeyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/our-story': {
      id: '/$locale/our-story'
      path: '/our-story'
      fullPath: '/$locale/our-story'
      preLoaderRoute: typeof LocaleOurStoryRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/property-for-sale-in-turkey': {
      id: '/$locale/property-for-sale-in-turkey'
      path: '/property-for-sale-in-turkey'
      fullPath: '/$locale/property-for-sale-in-turkey'
      preLoaderRoute: typeof LocalePropertyForSaleInTurkeyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/property-gallery': {
      id: '/$locale/property-gallery'
      path: '/property-gallery'
      fullPath: '/$locale/property-gallery'
      preLoaderRoute: typeof LocalePropertyGalleryRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/property-wizard': {
      id: '/$locale/property-wizard'
      path: '/property-wizard'
      fullPath: '/$locale/property-wizard'
      preLoaderRoute: typeof LocalePropertyWizardRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/testimonials': {
      id: '/$locale/testimonials'
      path: '/testimonials'
      fullPath: '/$locale/testimonials'
      preLoaderRoute: typeof LocaleTestimonialsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/turkish-citizenship-by-investment': {
      id: '/$locale/turkish-citizenship-by-investment'
      path: '/turkish-citizenship-by-investment'
      fullPath: '/$locale/turkish-citizenship-by-investment'
      preLoaderRoute: typeof LocaleTurkishCitizenshipByInvestmentRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/wizard-thank-you': {
      id: '/$locale/wizard-thank-you'
      path: '/wizard-thank-you'
      fullPath: '/$locale/wizard-thank-you'
      preLoaderRoute: typeof LocaleWizardThankYouRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$segment/$id': {
      id: '/$segment/$id'
      path: '/$segment/$id'
      fullPath: '/$segment/$id'
      preLoaderRoute: typeof SegmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ai-insights': {
      id: '/admin/ai-insights'
      path: '/ai-insights'
      fullPath: '/admin/ai-insights'
      preLoaderRoute: typeof AdminAiInsightsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/social-listening': {
      id: '/admin/social-listening'
      path: '/social-listening'
      fullPath: '/admin/social-listening'
      preLoaderRoute: typeof AdminSocialListeningRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/expenses-buying-property-turkey': {
      id: '/articles/expenses-buying-property-turkey'
      path: '/articles/expenses-buying-property-turkey'
      fullPath: '/articles/expenses-buying-property-turkey'
      preLoaderRoute: typeof ArticlesExpensesBuyingPropertyTurkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$segment/$id': {
      id: '/$locale/$segment/$id'
      path: '/$segment/$id'
      fullPath: '/$locale/$segment/$id'
      preLoaderRoute: typeof LocaleSegmentIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/article/$id': {
      id: '/$locale/article/$id'
      path: '/article/$id'
      fullPath: '/$locale/article/$id'
      preLoaderRoute: typeof LocaleArticleIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/articles/$slug': {
      id: '/$locale/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/$locale/articles/$slug'
      preLoaderRoute: typeof LocaleArticlesSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/articles/expenses-buying-property-turkey': {
      id: '/$locale/articles/expenses-buying-property-turkey'
      path: '/articles/expenses-buying-property-turkey'
      fullPath: '/$locale/articles/expenses-buying-property-turkey'
      preLoaderRoute: typeof LocaleArticlesExpensesBuyingPropertyTurkeyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/courses/': {
      id: '/$locale/courses/'
      path: '/courses'
      fullPath: '/$locale/courses/'
      preLoaderRoute: typeof LocaleCoursesIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/email': {
      id: '/admin/analytics/email'
      path: '/analytics/email'
      fullPath: '/admin/analytics/email'
      preLoaderRoute: typeof AdminAnalyticsEmailRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/heatmap': {
      id: '/admin/analytics/heatmap'
      path: '/analytics/heatmap'
      fullPath: '/admin/analytics/heatmap'
      preLoaderRoute: typeof AdminAnalyticsHeatmapRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/leads': {
      id: '/admin/analytics/leads'
      path: '/analytics/leads'
      fullPath: '/admin/analytics/leads'
      preLoaderRoute: typeof AdminAnalyticsLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/properties': {
      id: '/admin/analytics/properties'
      path: '/analytics/properties'
      fullPath: '/admin/analytics/properties'
      preLoaderRoute: typeof AdminAnalyticsPropertiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/realtime': {
      id: '/admin/analytics/realtime'
      path: '/analytics/realtime'
      fullPath: '/admin/analytics/realtime'
      preLoaderRoute: typeof AdminAnalyticsRealtimeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/traffic': {
      id: '/admin/analytics/traffic'
      path: '/analytics/traffic'
      fullPath: '/admin/analytics/traffic'
      preLoaderRoute: typeof AdminAnalyticsTrafficRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/ai': {
      id: '/admin/blog/ai'
      path: '/blog/ai'
      fullPath: '/admin/blog/ai'
      preLoaderRoute: typeof AdminBlogAiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/crm/': {
      id: '/admin/crm/'
      path: '/crm'
      fullPath: '/admin/crm/'
      preLoaderRoute: typeof AdminCrmIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/crm/contacts': {
      id: '/admin/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/admin/crm/contacts'
      preLoaderRoute: typeof AdminCrmContactsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/crm/tasks': {
      id: '/admin/crm/tasks'
      path: '/crm/tasks'
      fullPath: '/admin/crm/tasks'
      preLoaderRoute: typeof AdminCrmTasksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email/': {
      id: '/admin/email/'
      path: '/email'
      fullPath: '/admin/email/'
      preLoaderRoute: typeof AdminEmailIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email/inbox': {
      id: '/admin/email/inbox'
      path: '/email/inbox'
      fullPath: '/admin/email/inbox'
      preLoaderRoute: typeof AdminEmailInboxRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email/subscribers': {
      id: '/admin/email/subscribers'
      path: '/email/subscribers'
      fullPath: '/admin/email/subscribers'
      preLoaderRoute: typeof AdminEmailSubscribersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email/templates': {
      id: '/admin/email/templates'
      path: '/email/templates'
      fullPath: '/admin/email/templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/office/documents': {
      id: '/admin/office/documents'
      path: '/office/documents'
      fullPath: '/admin/office/documents'
      preLoaderRoute: typeof AdminOfficeDocumentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/office/spreadsheet': {
      id: '/admin/office/spreadsheet'
      path: '/office/spreadsheet'
      fullPath: '/admin/office/spreadsheet'
      preLoaderRoute: typeof AdminOfficeSpreadsheetRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/presentations/': {
      id: '/admin/presentations/'
      path: '/presentations'
      fullPath: '/admin/presentations/'
      preLoaderRoute: typeof AdminPresentationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/presentations/$id': {
      id: '/admin/presentations/$id'
      path: '/presentations/$id'
      fullPath: '/admin/presentations/$id'
      preLoaderRoute: typeof AdminPresentationsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/properties/': {
      id: '/admin/properties/'
      path: '/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AdminPropertiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/properties/new': {
      id: '/admin/properties/new'
      path: '/properties/new'
      fullPath: '/admin/properties/new'
      preLoaderRoute: typeof AdminPropertiesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/courses/$country/': {
      id: '/courses/$country/'
      path: '/courses/$country'
      fullPath: '/courses/$country/'
      preLoaderRoute: typeof CoursesCountryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$country/$moduleSlug': {
      id: '/courses/$country/$moduleSlug'
      path: '/courses/$country/$moduleSlug'
      fullPath: '/courses/$country/$moduleSlug'
      preLoaderRoute: typeof CoursesCountryModuleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$country/final-exam': {
      id: '/courses/$country/final-exam'
      path: '/courses/$country/final-exam'
      fullPath: '/courses/$country/final-exam'
      preLoaderRoute: typeof CoursesCountryFinalExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/courses/$country/': {
      id: '/$locale/courses/$country/'
      path: '/courses/$country'
      fullPath: '/$locale/courses/$country/'
      preLoaderRoute: typeof LocaleCoursesCountryIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/courses/$country/$moduleSlug': {
      id: '/$locale/courses/$country/$moduleSlug'
      path: '/courses/$country/$moduleSlug'
      fullPath: '/$locale/courses/$country/$moduleSlug'
      preLoaderRoute: typeof LocaleCoursesCountryModuleSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/courses/$country/final-exam': {
      id: '/$locale/courses/$country/final-exam'
      path: '/courses/$country/final-exam'
      fullPath: '/$locale/courses/$country/final-exam'
      preLoaderRoute: typeof LocaleCoursesCountryFinalExamRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/admin/crm/leads/': {
      id: '/admin/crm/leads/'
      path: '/crm/leads'
      fullPath: '/admin/crm/leads/'
      preLoaderRoute: typeof AdminCrmLeadsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/crm/leads/$id': {
      id: '/admin/crm/leads/$id'
      path: '/crm/leads/$id'
      fullPath: '/admin/crm/leads/$id'
      preLoaderRoute: typeof AdminCrmLeadsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email/campaigns/': {
      id: '/admin/email/campaigns/'
      path: '/email/campaigns'
      fullPath: '/admin/email/campaigns/'
      preLoaderRoute: typeof AdminEmailCampaignsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email/campaigns/$id': {
      id: '/admin/email/campaigns/$id'
      path: '/email/campaigns/$id'
      fullPath: '/admin/email/campaigns/$id'
      preLoaderRoute: typeof AdminEmailCampaignsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email/campaigns/new': {
      id: '/admin/email/campaigns/new'
      path: '/email/campaigns/new'
      fullPath: '/admin/email/campaigns/new'
      preLoaderRoute: typeof AdminEmailCampaignsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/properties/$id/': {
      id: '/admin/properties/$id/'
      path: '/properties/$id'
      fullPath: '/admin/properties/$id/'
      preLoaderRoute: typeof AdminPropertiesIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/properties/$id/edit': {
      id: '/admin/properties/$id/edit'
      path: '/properties/$id/edit'
      fullPath: '/admin/properties/$id/edit'
      preLoaderRoute: typeof AdminPropertiesIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleAboutUsRoute: typeof LocaleAboutUsRoute
  LocaleAiPropertySearchRoute: typeof LocaleAiPropertySearchRoute
  LocaleAliKaranRoute: typeof LocaleAliKaranRoute
  LocaleAntalyaRoute: typeof LocaleAntalyaRoute
  LocaleApartmentsForSaleInTurkeyRoute: typeof LocaleApartmentsForSaleInTurkeyRoute
  LocaleBaliRoute: typeof LocaleBaliRoute
  LocaleContactThankYouRoute: typeof LocaleContactThankYouRoute
  LocaleContactUsRoute: typeof LocaleContactUsRoute
  LocaleCyprusRoute: typeof LocaleCyprusRoute
  LocaleDesignYourHomeRoute: typeof LocaleDesignYourHomeRoute
  LocaleDubaiRoute: typeof LocaleDubaiRoute
  LocaleInformationRoute: typeof LocaleInformationRoute
  LocaleIstanbulRoute: typeof LocaleIstanbulRoute
  LocaleLuxuryVillasInTurkeyRoute: typeof LocaleLuxuryVillasInTurkeyRoute
  LocaleMapSearchRoute: typeof LocaleMapSearchRoute
  LocaleMersinRoute: typeof LocaleMersinRoute
  LocaleOffPlanPropertyTurkeyRoute: typeof LocaleOffPlanPropertyTurkeyRoute
  LocaleOurStoryRoute: typeof LocaleOurStoryRoute
  LocalePropertyForSaleInTurkeyRoute: typeof LocalePropertyForSaleInTurkeyRoute
  LocalePropertyGalleryRoute: typeof LocalePropertyGalleryRoute
  LocalePropertyWizardRoute: typeof LocalePropertyWizardRoute
  LocaleTestimonialsRoute: typeof LocaleTestimonialsRoute
  LocaleTurkishCitizenshipByInvestmentRoute: typeof LocaleTurkishCitizenshipByInvestmentRoute
  LocaleWizardThankYouRoute: typeof LocaleWizardThankYouRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleSegmentIdRoute: typeof LocaleSegmentIdRoute
  LocaleArticleIdRoute: typeof LocaleArticleIdRoute
  LocaleArticlesSlugRoute: typeof LocaleArticlesSlugRoute
  LocaleArticlesExpensesBuyingPropertyTurkeyRoute: typeof LocaleArticlesExpensesBuyingPropertyTurkeyRoute
  LocaleCoursesIndexRoute: typeof LocaleCoursesIndexRoute
  LocaleCoursesCountryModuleSlugRoute: typeof LocaleCoursesCountryModuleSlugRoute
  LocaleCoursesCountryFinalExamRoute: typeof LocaleCoursesCountryFinalExamRoute
  LocaleCoursesCountryIndexRoute: typeof LocaleCoursesCountryIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAboutUsRoute: LocaleAboutUsRoute,
  LocaleAiPropertySearchRoute: LocaleAiPropertySearchRoute,
  LocaleAliKaranRoute: LocaleAliKaranRoute,
  LocaleAntalyaRoute: LocaleAntalyaRoute,
  LocaleApartmentsForSaleInTurkeyRoute: LocaleApartmentsForSaleInTurkeyRoute,
  LocaleBaliRoute: LocaleBaliRoute,
  LocaleContactThankYouRoute: LocaleContactThankYouRoute,
  LocaleContactUsRoute: LocaleContactUsRoute,
  LocaleCyprusRoute: LocaleCyprusRoute,
  LocaleDesignYourHomeRoute: LocaleDesignYourHomeRoute,
  LocaleDubaiRoute: LocaleDubaiRoute,
  LocaleInformationRoute: LocaleInformationRoute,
  LocaleIstanbulRoute: LocaleIstanbulRoute,
  LocaleLuxuryVillasInTurkeyRoute: LocaleLuxuryVillasInTurkeyRoute,
  LocaleMapSearchRoute: LocaleMapSearchRoute,
  LocaleMersinRoute: LocaleMersinRoute,
  LocaleOffPlanPropertyTurkeyRoute: LocaleOffPlanPropertyTurkeyRoute,
  LocaleOurStoryRoute: LocaleOurStoryRoute,
  LocalePropertyForSaleInTurkeyRoute: LocalePropertyForSaleInTurkeyRoute,
  LocalePropertyGalleryRoute: LocalePropertyGalleryRoute,
  LocalePropertyWizardRoute: LocalePropertyWizardRoute,
  LocaleTestimonialsRoute: LocaleTestimonialsRoute,
  LocaleTurkishCitizenshipByInvestmentRoute:
    LocaleTurkishCitizenshipByInvestmentRoute,
  LocaleWizardThankYouRoute: LocaleWizardThankYouRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleSegmentIdRoute: LocaleSegmentIdRoute,
  LocaleArticleIdRoute: LocaleArticleIdRoute,
  LocaleArticlesSlugRoute: LocaleArticlesSlugRoute,
  LocaleArticlesExpensesBuyingPropertyTurkeyRoute:
    LocaleArticlesExpensesBuyingPropertyTurkeyRoute,
  LocaleCoursesIndexRoute: LocaleCoursesIndexRoute,
  LocaleCoursesCountryModuleSlugRoute: LocaleCoursesCountryModuleSlugRoute,
  LocaleCoursesCountryFinalExamRoute: LocaleCoursesCountryFinalExamRoute,
  LocaleCoursesCountryIndexRoute: LocaleCoursesCountryIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAiInsightsRoute: typeof AdminAiInsightsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSocialListeningRoute: typeof AdminSocialListeningRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticsEmailRoute: typeof AdminAnalyticsEmailRoute
  AdminAnalyticsHeatmapRoute: typeof AdminAnalyticsHeatmapRoute
  AdminAnalyticsLeadsRoute: typeof AdminAnalyticsLeadsRoute
  AdminAnalyticsPropertiesRoute: typeof AdminAnalyticsPropertiesRoute
  AdminAnalyticsRealtimeRoute: typeof AdminAnalyticsRealtimeRoute
  AdminAnalyticsTrafficRoute: typeof AdminAnalyticsTrafficRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogAiRoute: typeof AdminBlogAiRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminCrmContactsRoute: typeof AdminCrmContactsRoute
  AdminCrmTasksRoute: typeof AdminCrmTasksRoute
  AdminEmailInboxRoute: typeof AdminEmailInboxRoute
  AdminEmailSubscribersRoute: typeof AdminEmailSubscribersRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminOfficeDocumentsRoute: typeof AdminOfficeDocumentsRoute
  AdminOfficeSpreadsheetRoute: typeof AdminOfficeSpreadsheetRoute
  AdminPresentationsIdRoute: typeof AdminPresentationsIdRoute
  AdminPropertiesNewRoute: typeof AdminPropertiesNewRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCrmIndexRoute: typeof AdminCrmIndexRoute
  AdminEmailIndexRoute: typeof AdminEmailIndexRoute
  AdminPresentationsIndexRoute: typeof AdminPresentationsIndexRoute
  AdminPropertiesIndexRoute: typeof AdminPropertiesIndexRoute
  AdminCrmLeadsIdRoute: typeof AdminCrmLeadsIdRoute
  AdminEmailCampaignsIdRoute: typeof AdminEmailCampaignsIdRoute
  AdminEmailCampaignsNewRoute: typeof AdminEmailCampaignsNewRoute
  AdminPropertiesIdEditRoute: typeof AdminPropertiesIdEditRoute
  AdminCrmLeadsIndexRoute: typeof AdminCrmLeadsIndexRoute
  AdminEmailCampaignsIndexRoute: typeof AdminEmailCampaignsIndexRoute
  AdminPropertiesIdIndexRoute: typeof AdminPropertiesIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAiInsightsRoute: AdminAiInsightsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSocialListeningRoute: AdminSocialListeningRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticsEmailRoute: AdminAnalyticsEmailRoute,
  AdminAnalyticsHeatmapRoute: AdminAnalyticsHeatmapRoute,
  AdminAnalyticsLeadsRoute: AdminAnalyticsLeadsRoute,
  AdminAnalyticsPropertiesRoute: AdminAnalyticsPropertiesRoute,
  AdminAnalyticsRealtimeRoute: AdminAnalyticsRealtimeRoute,
  AdminAnalyticsTrafficRoute: AdminAnalyticsTrafficRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogAiRoute: AdminBlogAiRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminCrmContactsRoute: AdminCrmContactsRoute,
  AdminCrmTasksRoute: AdminCrmTasksRoute,
  AdminEmailInboxRoute: AdminEmailInboxRoute,
  AdminEmailSubscribersRoute: AdminEmailSubscribersRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminOfficeDocumentsRoute: AdminOfficeDocumentsRoute,
  AdminOfficeSpreadsheetRoute: AdminOfficeSpreadsheetRoute,
  AdminPresentationsIdRoute: AdminPresentationsIdRoute,
  AdminPropertiesNewRoute: AdminPropertiesNewRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCrmIndexRoute: AdminCrmIndexRoute,
  AdminEmailIndexRoute: AdminEmailIndexRoute,
  AdminPresentationsIndexRoute: AdminPresentationsIndexRoute,
  AdminPropertiesIndexRoute: AdminPropertiesIndexRoute,
  AdminCrmLeadsIdRoute: AdminCrmLeadsIdRoute,
  AdminEmailCampaignsIdRoute: AdminEmailCampaignsIdRoute,
  AdminEmailCampaignsNewRoute: AdminEmailCampaignsNewRoute,
  AdminPropertiesIdEditRoute: AdminPropertiesIdEditRoute,
  AdminCrmLeadsIndexRoute: AdminCrmLeadsIndexRoute,
  AdminEmailCampaignsIndexRoute: AdminEmailCampaignsIndexRoute,
  AdminPropertiesIdIndexRoute: AdminPropertiesIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  SlugRoute: SlugRoute,
  AboutUsRoute: AboutUsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AiPropertySearchRoute: AiPropertySearchRoute,
  AliKaranRoute: AliKaranRoute,
  AntalyaRoute: AntalyaRoute,
  ApartmentsForSaleInTurkeyRoute: ApartmentsForSaleInTurkeyRoute,
  BaliRoute: BaliRoute,
  ContactThankYouRoute: ContactThankYouRoute,
  ContactUsRoute: ContactUsRoute,
  CyprusRoute: CyprusRoute,
  DesignYourHomeRoute: DesignYourHomeRoute,
  DubaiRoute: DubaiRoute,
  InformationRoute: InformationRoute,
  IstanbulRoute: IstanbulRoute,
  LuxuryVillasInTurkeyRoute: LuxuryVillasInTurkeyRoute,
  MapSearchRoute: MapSearchRoute,
  MersinRoute: MersinRoute,
  OffPlanPropertyTurkeyRoute: OffPlanPropertyTurkeyRoute,
  OurStoryRoute: OurStoryRoute,
  PropertyForSaleInTurkeyRoute: PropertyForSaleInTurkeyRoute,
  PropertyGalleryRoute: PropertyGalleryRoute,
  PropertyWizardRoute: PropertyWizardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  TurkishCitizenshipByInvestmentRoute: TurkishCitizenshipByInvestmentRoute,
  WizardThankYouRoute: WizardThankYouRoute,
  SegmentIdRoute: SegmentIdRoute,
  ArticleIdRoute: ArticleIdRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesExpensesBuyingPropertyTurkeyRoute:
    ArticlesExpensesBuyingPropertyTurkeyRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesCountryModuleSlugRoute: CoursesCountryModuleSlugRoute,
  CoursesCountryFinalExamRoute: CoursesCountryFinalExamRoute,
  CoursesCountryIndexRoute: CoursesCountryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
