-- Insert Mersin properties with correct ref_no and images
INSERT INTO public.properties (
  ref_no, title, location, price, bedrooms, bathrooms, status, property_type, 
  description, property_image, facilities, agent_name, agent_phone_number,
  distance_to_airport_km, distance_to_beach_km, building_complete_date
) VALUES 
(
  '3001',
  'Spacious apartments within walking distance to the sea',
  'Mersin',
  '€57,000',
  '1+1 <> 2+1',
  '1 <> 2',
  'Under Construction',
  'Apartments',
  'Modern apartment complex in Mersin with sea view and contemporary design.',
  'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop',
  'Sea View, Pool, Gym, Parking, Security',
  'Ervina Köksel',
  '+905523032750',
  '15',
  '0.5',
  '01/01/2025'
),
(
  '3002',
  'Luxury villa complex with marina access',
  'Mersin, Marina District',
  '€180,000',
  '3+1 <> 4+1',
  '2 <> 3',
  'Under Construction',
  'Villas',
  'Premium villa development with direct marina access and modern amenities.',
  'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop',
  'Marina Access, Private Garden, Pool, Parking, Security',
  'Ervina Köksel',
  '+905523032750',
  '12',
  '0.2',
  '01/01/2025'
),
(
  '3003',
  'Modern apartments with sea view',
  'Mersin, Coastal Area',
  '€95,000',
  '2+1 <> 3+1',
  '2 <> 3',
  'Under Construction',
  'Apartments',
  'Contemporary apartment complex with stunning sea views and modern facilities.',
  'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
  'Sea View, Pool, Fitness Center, Parking, Security',
  'Ervina Köksel',
  '+905523032750',
  '18',
  '0.1',
  '06/01/2025'
)
ON CONFLICT (ref_no) DO UPDATE SET
  title = EXCLUDED.title,
  location = EXCLUDED.location,
  price = EXCLUDED.price,
  bedrooms = EXCLUDED.bedrooms,
  bathrooms = EXCLUDED.bathrooms,
  status = EXCLUDED.status,
  property_type = EXCLUDED.property_type,
  description = EXCLUDED.description,
  property_image = EXCLUDED.property_image,
  facilities = EXCLUDED.facilities,
  agent_name = EXCLUDED.agent_name,
  agent_phone_number = EXCLUDED.agent_phone_number,
  distance_to_airport_km = EXCLUDED.distance_to_airport_km,
  distance_to_beach_km = EXCLUDED.distance_to_beach_km,
  building_complete_date = EXCLUDED.building_complete_date,
  updated_at = NOW();