-- Insert testimonials from CSV data
INSERT INTO public.testimonials (customer_name, review_text, image_url, location, property_type, rating) VALUES
('Mrs. Cansel & Mr. Ihsan', 'Happy customers who bought an apartment from Antalya, Altıntaş and received their title deeds.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/1-1.png', 'Antalya, Altıntaş', 'apartment', 5),
('İbrahim', 'Happy customer who bought an apartment in Mersin from our company and received his title deed!', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/charlie.png', 'Mersin', 'apartment', 5),
('Charlie', 'Happy customer who bought an apartment in Mersin, Erdemli from our company.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/1.png', 'Mersin, Erdemli', 'apartment', 5),
('Josef', 'Happy customer who bought several apartments from our company in Antalya, Altıntaş.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/mrs-mahnoor.png', 'Antalya, Altıntaş', 'apartment', 5),
('Mahnoor', 'Happy customer who bought a 1+1 apartment in Antalya, Altıntaş from our company.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/doseme6.png', 'Antalya, Altıntaş', 'apartment', 5),
('Gönül', 'Happy customer who bought a land in Antalya, Döşemealtı from our company.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/turgay.png', 'Antalya, Döşemealtı', 'land', 5),
('Turgay', 'Happy customer who bought an apartment from our company in Antalya and received his title deed.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/turgut.png', 'Antalya', 'apartment', 5),
('Turgut', 'Happy customer who bought an apartment in Antalya, Altıntaş from our company and received his title deed.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/2-1.%5B1%5D.jpg', 'Antalya, Altıntaş', 'apartment', 5),
('Josef', 'Happy Customer who bought two 2+1 apartments from our company in Altıntaş, Antalya.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/2-1.jpg', 'Altıntaş, Antalya', 'apartment', 5),
('Mert', 'Happy customer who bought an apartment from our company in Antalya.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/23.jpg', 'Antalya', 'apartment', 5),
('Salih', 'Happy customers who bought 3+1 apartment from at Dösemealti, Antalya from our company.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/2.jpg', 'Dösemealti, Antalya', 'apartment', 5),
('Sofiane & Yacine Belhadef', 'Happy customers who bought 2+1 apartment from our company and receiving his title deed this week.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/ghursaran.jpg', NULL, 'apartment', 5),
('Ghursaran', 'Happy customer who bought apartment from Dubai from our company.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/amirtestimonials.jpg', 'Dubai', 'apartment', 5),
('Amir', 'Happy customer who bought 2 apartment from our company and receiving his title deed this week.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/utku---turkiye.png', NULL, 'apartment', 5),
('Utku', 'Happy customer who bought 2+1 flat in Antalya.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/1.jpg', 'Antalya', 'flat', 5),
('Abdul', 'Bought apartment from our company and receiving his title deed this week.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/shelina2.jpg', NULL, 'apartment', 5),
('Shelina', 'Happy Customer who bought an apartment from our Company in Antalya.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/azatullah2.jpg', 'Antalya', 'apartment', 5),
('Azatullah', 'Happy Customer purchased a 2+1 apartment and a 1+1 apartment in Antalya from our company.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/t.jpg', 'Antalya', 'apartment', 5),
('Oğuzhan', 'Happy Customer purchased a duplex apartment in Antalya from our company and received his title deed within one week.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/baris2.jpg', 'Antalya', 'duplex apartment', 5),
('Halima', 'Happy customer who bought 1+1 fully furnished apartment in Konyaaltı, Antalya from Future Homes', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/whatsapp-image-2024-12-15-at-16-07-33.jpg', 'Konyaaltı, Antalya', 'apartment', 5),
('Mehmet', 'Happy customer who bought 2+1 apartment in Antalya from our company', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/whatsapp-image-2024-11-10-at-10-35-52.jpg', 'Antalya', 'apartment', 5),
('Mustafa', 'I am very happy that i bought apartment from this company and i received my title deed within 1 week. Are you looking to buy from this company, do not hesitate.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/whatsapp-image-2024-10-24-at-16-45-50.jpg', NULL, 'apartment', 5),
('Aydogan', 'Happy customer who bought apartment from our company.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/whatsapp-image-2024-10-08-at-16-38-03.jpg', NULL, 'apartment', 5),
('Yana', 'Happy customer who bought apartment from Future Homes', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/whatsapp-image-2024-10-07-at-14-42-07.jpg', NULL, 'apartment', 5),
('Luiza', 'I have bought two apartments this year in Mersin. I got help with everything. Many thanks to both Kim and Ali. They are skilled and efficient.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/whatsapp-image-2024-09-17-at-11-19-37.jpg', 'Mersin', 'apartment', 5),
('Cuneyt', 'Would like to start off by giving a big Thank you to Future Homes. A very reliable trustable estate agency company. The service they pride is top level & there communication level is amazing. They are very helpful & always there for you. Highly recommend with an A* Ali Bey the owner of Future Homes & his team Tolga & Bariş Thank you guys so much for everything & hope to deal with you again. You guys treated me like i was apart of a family member of yours than a customer!', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/whatsapp-image-2024-09-05-at-16-33-11.jpg', NULL, NULL, 5),
('Yasar', 'Happy customer who bought 2 exclusive apartments from Future Homes in Antalya', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/whatsapp-image-2024-07-26-at-11-28-15.jpg', 'Antalya', 'apartment', 5),
('Mody', 'Happy customer who bought apartment from Future Homes,', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/whatsapp-image-2024-07-18-at-09-43-29-1.jpg', NULL, 'apartment', 5),
('Ibrahim', 'Happy customer who bought apartment in Antalya from our company.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/whatsapp-image-2024-06-25-at-14-29-37.jpg', 'Antalya', 'apartment', 5),
('Jens', 'Happy customer who bought apartment in Antalya from Future Homes', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/whatsapp-image-2024-05-28-at-15-10-51.jpg', 'Antalya', 'apartment', 5),
('Dahlia', 'Happy customer who bought apartment from our Antalya Branch.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/0bd9877b-e3ec-4840-9f63-aea16caa5649.jpg', 'Antalya', 'apartment', 5),
('Lena', 'I definitely recommend it. I consider myself very lucky that I found this company. I was looking for an apartment in Antalya near the airport. Real estate agents Barish and Tolga did their job quickly and accurately. First, they studied my request in detail. Only when they were convinced that they understood me correctly did they prepare a sheet of proposals for me. We went out to look at apartments several times. They discussed and clarified my wishes. We found a suitable option and helped prepare documents and calculate all payments. After purchasing the apartment, they offered me help in finding and purchasing furniture and appliances. I communicated with them in English. Thank you for your care and correct behavior. I wish you more grateful clients', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/801cf32b-de42-471b-941a-e21cfef0875a.jpg', 'Antalya', 'apartment', 5),
('Rizwan', 'Happy customer who bought apartment in Mersin and got his title deed.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/whatsapp-image-2023-10-16-at-10-20-03.jpg', 'Mersin', 'apartment', 5),
('Belhadef Sofiane Gaya', 'Recently, we bought an apartment with Future Home, which is an excellent agency that I highly recommend, particularly Mr. Tolga and his colleague Mr. Baris who advised us well and assisted throughout the process, thank you very much.', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/dollyz.jpg', NULL, 'apartment', 5),
('Dollyz', 'Tolga was a Very professional person who take good care of every single thing to do for this matter and myself i recommend them strongly', 'https://futurehomesturkey.com/resize/1200/uploads/happy_customer/omar-el-chak.jpg', NULL, NULL, 5),
('Omar el chal', 'Happy customer who bought apartment in Antalya from Future Homes', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/A43E0E6F-AC6C-485B-BEEA-EDB46B2EE8B0.jpg', 'Antalya', 'apartment', 5),
('Parwez', 'Amazing team, i bought apartment in Mersin from Future Homes and Ali. Proffesional.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/C31E6A9C-4561-4F5E-AEA8-746B989E4FC3.jpg', 'Mersin', 'apartment', 5),
('Lina', 'Trustable, proffesional and very helpful people and company. Bought 4 apartments from Future Homes. Recommending.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/WhatsApp%20Image%202023-05-02%20at%2010-19-44.jpg', NULL, 'apartment', 5),
('Alex', 'Happy customer who bought apartment in Antalya from Future Homes and Elena.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/DCDA43D0-4B7F-4779-ADFA-455D1B0F7464.jpg', 'Antalya', 'apartment', 5),
('Mahonzi', 'We were going to buy an apartment in Turkey and got in touch with Future Homes. There we spoke with Ali Karan. We had many questions that needed to be answered before we decided to buy an apartment. Ali followed us up all the way. Answered all questions and made the process pleasant and orderly. Thanks for the great help. Are you looking for an apartment in Turkey, but don''t know where to start? Talk to Ali Karan', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/WhatsApp%20Image%202023-04-12%20at%2015-31-01.jpg', NULL, 'apartment', 5),
('Singh', 'I am UK citizen who purchased apartment for investment in Turkey and i came cross Mr.Ali Karan from Future Homes. I have dealt with another agencies across Turkey with my investment portfolio, but i can most certainly guarentee you that my experience with Ali Karan was absolutely outstanding. His response to all my questions and information has been incredibly knowledgeable.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/WhatsApp%20Image%202023-04-11%20at%2017-04-34.jpg', NULL, 'apartment', 5),
('Sarkar Hassan', 'Incredibly good service and very good follow-up. Reassuring and efficient team! Kim S. and Ali Karan are highly recommended!', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/WhatsApp%20Image%202023-02-28%20at%2012-35-36.jpg', NULL, NULL, 5),
('Mohamed', 'Best company in Turkey, so happy to get my title deed. Thank you Future Homes and Tolga.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/referanss11.jpg', NULL, NULL, 5),
('Yurii Glushkov', 'Happy customer who bought apartment in Kemer from Future Homes and Elena.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/olga-referans.jpg', 'Kemer', 'apartment', 5),
('Olga', 'Bought our first apartment in Turkey with Future Homes. Very quick responses to any type of question that we had, everything is explained clearly and thoroughly. Advisor Elena is super knowledgeable, friendly and listened to every need we had. Great customer service, trustworthy company. Hopefully will help us with purchasing more properties. Highly recommend to anyone looking to buy in Turkey.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/tahir-referans.jpg', NULL, 'apartment', 5),
('Tahir', 'Had a great experience with Future Homes Antalya. Pleasant and welcoming staff with great expertise. Well organized, honest and reassuring. Both Mikail, Tolga and Cem have been welcoming and cooperative. Big praise from us.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/WhatsApp%20Image%202022-09-24%20at%2012.41.11.jpeg', 'Antalya', NULL, 5),
('Peker', 'First of all thank you so much to Mr.Cem and Future Homes for all the help, i was scared to buy apartments which is under construction but in the end i bought 3 apartments from Future Homes. I definitely recommend this company if you want to buy an apartment.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/oksana-referans.jpg', NULL, 'apartment', 5),
('Oksana', 'Happy customer who bought apartment from Elena and Future Homes today.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/PHOTO-2022-08-13-11-15-54.jpg', NULL, 'apartment', 5),
('Zaid', 'I bought an apartment in Avsallar through Ali. A very nice and helpful guy who can of course fix everything! Highly recommended', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/norway.jpg', 'Avsallar', 'apartment', 5),
('Kharon', 'Bought totally 2 apartments through Future Homes by recommendation from our friends. Very happy.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/Poliakov%20-%20Russia-referans.jpg', NULL, 'apartment', 5),
('Poliakov', 'Bought apartment through Future Homes and Ksenia, very satisfied with all the help and service.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/rus-referans.jpg', NULL, 'apartment', 5),
('Nikolaus', 'Friends don''t doubt

I recommend only contacting Future Homes

You are sure to be pleasantly surprised here. Future Homes team!!!

Hello to everyone who is planning to buy apartments in Turkey.

I recently bought 2 apartments in a complex in Antalya from Future Homes. I''m going to buy another one in the near future. I am very pleased with the service and the help I received. I can only recommend Future Homes.

Special thanks to Ksenia for her support in all matters.

Great team, professional approach!', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/abdulla.jpg', 'Antalya', 'apartment', 5),
('Abdulla', 'Definitely recommending Future Homes if you want to purchase apartment overseas, they was with me through all the process. Thank you Tolga and Ksenia from Future Homes.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/testimonials/1(1).jpg', NULL, 'apartment', 5),
('Haron and Larisa', 'Friends bought apartment at Fly port Residence and recommended us the complex and we are also happy customers from Future Homes now.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/magomed%20-%20tesminatiols.jpg', 'Fly port Residence', 'apartment', 5),
('Magomed and Asetta', 'Great service!

I can recommend you Ali Karan with a clear conscience.

He is very serious, honest and helpful.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/testimonials/testblain.jpg', NULL, NULL, 5),
('Blaine', '4 apartments bought through Future Homes and Ali Karan and 4 title deed recivied, very satisfied.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/mr-blain.jpg', NULL, 'apartment', 5),
('Linda', 'Will keep it short, We are pleased with everything.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/referans2.jpg', NULL, NULL, 5),
('Subhi', 'We bought an apartment through Future Homes. Wonderful service. Many thanks to everyone on the team, very happy! Highly recommend.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/referans3.jpg', NULL, 'apartment', 5),
('Nasir', 'We was searching to buy one apartment each and found Future Homes in Antalya, we was very satisfied with the work the team made for us and helped us thru every step. Thank you Future Homes.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/m%C3%BC%C5%9Fteri2.jpg', 'Antalya', 'apartment', 5),
('Vicdan', 'Bought apartment in Alanya, Avsallar. Came as a referral customer from my friend in Sweden. Recommending Future Homes if you want to purchase flat in Turkey', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/referans-25-02.jpg', 'Alanya, Avsallar', 'flat', 5),
('Maher Loul', 'Very proffesional company. I purchased a very nice apartment in a complex in Antalya. Thank you Future Homes', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/Referans.jpg', 'Antalya', 'apartment', 5),
('Mohamed', 'Bought 3 apartments in Fly Port Residence in Antalya, Altintas from Future Homes and a happy customer.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/cansel-ihsan.jpg', 'Antalya, Altintas', 'apartment', 5),
('Cansel Aykut', 'We made online viewing tour with Ali Karan at Future Homes, we was very interested in Fly Port Residence and finally after decision with my husband we bought a nice apartment there. I definitely recommend Future Homes for the future buyers.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/Abouaoun%2C%20Sweden.jpg', 'Fly Port Residence', 'apartment', 5),
('Abouaoun', 'Hello, We have recently completed the purchase of 3 apartments in a complex in Antalya from Future Homes, we are very satisfied with the service and help we received. We recommend Future Homes if you want to buy property in Turkey. Today i got my 3 title deeds.', 'https://cdn.futurehomesturkey.com/resize/1200/uploads/files/Adam%20Ahmad%20Ismail.jpg', 'Antalya', 'apartment', 5),
('Adam Ahmad Ismail', 'I''m really happy with the Ali at Future Homes. Everything has gone smoothly and it has been a safe business. From the beginning when he showed the apartment until today when we signed for the team (Tapun). I give him 10 stars for his service.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/16.jpeg', NULL, 'apartment', 5),
('Sharokh', 'Firstly i am very happy to say that i got all my 3 title deed yesterday, and i am very happy with the help i got during all the process and even with the aftersale service. Ali and Future Homes team was always with me, and whatever the time is(morning,afternoon,night etc...he always answer me and always is there for me) I definitely recommend you to call Future Homes if you are interested to purchase in Turkey.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/14.jpg', NULL, NULL, 5),
('Amir', 'I am very happy with the purchase I made from Future Homes and Ali Karan, a very honest and professional man who helped me throughout the purchase and even after.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/13.jpg', NULL, NULL, 5),
('Huseyin', 'I definitely recommend Future Homes if you are looking to invest in Turkey.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/9.jpeg', NULL, NULL, 5),
('Dana', 'Very professional treatment. A young company with great ambitions that works hard for the customer to undergo a secure real estate transaction. They focus on the long term and care about the relationship.

+ Committed

+ Knowledgeable

+ Humble

+ Nice welcome and good service.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/7.jpeg', NULL, NULL, 5),
('Ihsan', 'I was searching to invest in apartment in Antalya and found Ali Karan and Future Homes at google, i am very happy that they helped me thru all the process.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/6.jpeg', 'Antalya', 'apartment', 5),
('Ibrahim', 'Hello, We have recently completed the purchase of 3 apartments in a complex in Antalya from Future Homes, we are very satisfied with the service and help we received. We recommend Future Homes if you want to buy property in Turkey.', 'https://futurehomesturkey.com/resize/1200/uploads/files/testimonials/3.jpg', 'Antalya', 'apartment', 5);