-- Add 7 more Dubai properties to reach 35 total
INSERT INTO properties (
  id, title, location, price, description, property_url, property_image, starting_price_eur, 
  property_type, bedrooms, bathrooms, building_complete_date, sizes_m2, distance_to_airport_km, 
  distance_to_beach_km, agent_name, agent_phone_number, ref_no, status, property_images, 
  property_prices_by_room, property_district, facilities
) VALUES
-- Property 10052
(
  gen_random_uuid(),
  'Luxury waterfront apartments with marina views in Dubai, Dubai Marina',
  'Dubai, Dubai Marina',
  '€850,000',
  'Apartments for sale are located in Dubai Marina. Dubai Marina is one of the most prestigious and sought-after areas for real estate investment in Dubai. With its stunning waterfront location, world-class marina facilities, luxury shopping destinations, and vibrant nightlife, the area offers exceptional rental yields and capital appreciation potential. The area is home to some of the world''s tallest residential towers and provides easy access to key business districts and tourist attractions.',
  'https://futurehomesturkey.com/en/estate/ad.php?id=4701',
  'https://cdn.futurehomesturkey.com/uploads/thumbs/pages/4701/general/apartment-322001.webp',
  '850000',
  'Apartments',
  '2+1 <> 4+1',
  '2 <> 4',
  '12/01/2026',
  '120 <> 280',
  '25',
  '2',
  'Maria Andersson',
  '+90 552 303 27 50',
  '10052',
  'Under Construction',
  ARRAY[
    'https://cdn.futurehomesturkey.com/uploads/pages/4701/general/apartment-322001.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4701/general/apartment-322002.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4701/interior/apartment-322003.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4701/interior/apartment-322004.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4701/plan/apartment-322005.webp'
  ],
  '2+1 (Flat) - 120m² - €850,000; 3+1 (Flat) - 180m² - €1,250,000; 4+1 (Flat) - 280m² - €1,850,000',
  'Dubai Marina',
  'Marina View,Private Beach Access,Infinity Pool,Spa,Gym,Concierge,Valet Parking,Yacht Club Access,Rooftop Terrace,Smart Home,From Developer,Under Construction,Luxury'
),
-- Property 10053
(
  gen_random_uuid(),
  'Premium golf course apartments in Dubai, Dubai Hills Estate',
  'Dubai, Dubai Hills Estate',
  '€695,000',
  'Apartments for sale are located in Dubai Hills Estate. Dubai Hills Estate is a master-planned community that offers a perfect blend of urban living and natural landscapes. The development features an 18-hole championship golf course, extensive parks, and is strategically located between Downtown Dubai and Dubai Marina, making it an ideal choice for both families and investors.',
  'https://futurehomesturkey.com/en/estate/ad.php?id=4702',
  'https://cdn.futurehomesturkey.com/uploads/thumbs/pages/4702/general/apartment-322101.webp',
  '695000',
  'Apartments',
  '1+1 <> 3+1',
  '1 <> 3',
  '08/01/2027',
  '85 <> 195',
  '20',
  '15',
  'Ahmed Hassan',
  '+90 552 303 27 50',
  '10053',
  'Under Construction',
  ARRAY[
    'https://cdn.futurehomesturkey.com/uploads/pages/4702/general/apartment-322101.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4702/general/apartment-322102.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4702/interior/apartment-322103.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4702/plan/apartment-322104.webp'
  ],
  '1+1 (Flat) - 85m² - €695,000; 2+1 (Flat) - 135m² - €950,000; 3+1 (Flat) - 195m² - €1,350,000',
  'Dubai Hills Estate',
  'Golf Course View,Community Pool,Fitness Center,Tennis Court,Children''s Play Area,BBQ Area,Walking Trails,Cycling Tracks,24/7 Security,Smart Home,From Developer,Under Construction'
),
-- Property 10054
(
  gen_random_uuid(),
  'Contemporary studio and 1-bedroom apartments in Dubai, Business Bay',
  'Dubai, Business Bay',
  '€385,000',
  'Apartments for sale are located in Business Bay, Dubai. Business Bay is Dubai''s central business district, offering excellent connectivity to key areas and landmarks. The area is home to numerous multinational corporations, luxury hotels, and shopping destinations. It provides excellent investment opportunities with high rental demand from business professionals.',
  'https://futurehomesturkey.com/en/estate/ad.php?id=4703',
  'https://cdn.futurehomesturkey.com/uploads/thumbs/pages/4703/general/apartment-322201.webp',
  '385000',
  'Apartments',
  'Studio <> 1+1',
  '1 <> 2',
  '05/01/2026',
  '45 <> 85',
  '18',
  '12',
  'Sofia Lindberg',
  '+90 552 303 27 50',
  '10054',
  'Under Construction',
  ARRAY[
    'https://cdn.futurehomesturkey.com/uploads/pages/4703/general/apartment-322201.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4703/interior/apartment-322202.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4703/plan/apartment-322203.webp'
  ],
  'Studio (Flat) - 45m² - €385,000; 1+1 (Flat) - 85m² - €595,000',
  'Business Bay',
  'City View,Business District,Pool,Gym,Rooftop Terrace,High Speed Internet,24/7 Security,Concierge,Metro Access,From Developer,Under Construction'
),
-- Property 10055
(
  gen_random_uuid(),
  'Exclusive penthouses with panoramic views in Dubai, Palm Jumeirah',
  'Dubai, Palm Jumeirah',
  '€2,950,000',
  'Penthouses for sale are located on Palm Jumeirah, Dubai. Palm Jumeirah is one of the world''s most iconic residential destinations, offering unparalleled luxury living with private beaches, world-class amenities, and stunning views of the Arabian Gulf. This man-made island represents the pinnacle of Dubai''s real estate market.',
  'https://futurehomesturkey.com/en/estate/ad.php?id=4704',
  'https://cdn.futurehomesturkey.com/uploads/thumbs/pages/4704/general/apartment-322301.webp',
  '2950000',
  'Penthouses',
  '3+1 <> 5+1',
  '3 <> 5',
  '10/01/2025',
  '250 <> 450',
  '35',
  '0',
  'Lars Eriksson',
  '+90 552 303 27 50',
  '10055',
  'Ready',
  ARRAY[
    'https://cdn.futurehomesturkey.com/uploads/pages/4704/general/apartment-322301.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4704/interior/apartment-322302.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4704/interior/apartment-322303.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4704/plan/apartment-322304.webp'
  ],
  '3+1 (Penthouse) - 250m² - €2,950,000; 4+1 (Penthouse) - 350m² - €4,200,000; 5+1 (Penthouse) - 450m² - €5,800,000',
  'Palm Jumeirah',
  'Sea View,Private Beach,Infinity Pool,Private Elevator,Maid''s Room,Driver''s Room,Private Parking,Yacht Berth,Spa,Gym,Concierge,Luxury,Ready'
),
-- Property 10056
(
  gen_random_uuid(),
  'Smart apartments with flexible payment plans in Dubai, Arabian Ranches',
  'Dubai, Arabian Ranches',
  '€525,000',
  'Apartments for sale are located in Arabian Ranches, Dubai. Arabian Ranches is a well-established family-friendly community known for its golf courses, polo club, and tranquil desert setting. The area offers a unique blend of luxury living with a suburban feel, making it popular among families and long-term residents.',
  'https://futurehomesturkey.com/en/estate/ad.php?id=4705',
  'https://cdn.futurehomesturkey.com/uploads/thumbs/pages/4705/general/apartment-322401.webp',
  '525000',
  'Apartments',
  '2+1 <> 3+1',
  '2 <> 3',
  '15/01/2027',
  '110 <> 165',
  '28',
  '25',
  'Emma Johansson',
  '+90 552 303 27 50',
  '10056',
  'Under Construction',
  ARRAY[
    'https://cdn.futurehomesturkey.com/uploads/pages/4705/general/apartment-322401.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4705/interior/apartment-322402.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4705/plan/apartment-322403.webp'
  ],
  '2+1 (Flat) - 110m² - €525,000; 3+1 (Flat) - 165m² - €785,000',
  'Arabian Ranches',
  'Golf Course Community,Family Friendly,Polo Club,Desert Views,Community Pool,Tennis Court,Cycling Tracks,Equestrian Center,24/7 Security,Smart Home,From Developer,Under Construction'
),
-- Property 10057
(
  gen_random_uuid(),
  'High-rise apartments with Burj Khalifa views in Dubai, DIFC',
  'Dubai, DIFC',
  '€1,150,000',
  'Apartments for sale are located in DIFC (Dubai International Financial Centre). DIFC is Dubai''s leading financial hub and one of the most prestigious business districts in the Middle East. The area offers excellent connectivity, world-class amenities, and represents the heart of Dubai''s financial sector, making it highly attractive for investment.',
  'https://futurehomesturkey.com/en/estate/ad.php?id=4706',
  'https://cdn.futurehomesturkey.com/uploads/thumbs/pages/4706/general/apartment-322501.webp',
  '1150000',
  'Apartments',
  '1+1 <> 3+1',
  '1 <> 3',
  '22/01/2026',
  '95 <> 220',
  '15',
  '18',
  'Olof Pettersson',
  '+90 552 303 27 50',
  '10057',
  'Under Construction',
  ARRAY[
    'https://cdn.futurehomesturkey.com/uploads/pages/4706/general/apartment-322501.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4706/interior/apartment-322502.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4706/plan/apartment-322503.webp'
  ],
  '1+1 (Flat) - 95m² - €1,150,000; 2+1 (Flat) - 160m² - €1,750,000; 3+1 (Flat) - 220m² - €2,450,000',
  'DIFC',
  'Burj Khalifa View,Financial District,Metro Access,Business Center,Rooftop Pool,Sky Lounge,Valet Parking,Concierge,High Speed Internet,24/7 Security,Luxury,From Developer,Under Construction'
),
-- Property 10058
(
  gen_random_uuid(),
  'Beachfront luxury residences in Dubai, Jumeirah Beach Residence',
  'Dubai, Jumeirah Beach Residence',
  '€975,000',
  'Apartments for sale are located in Jumeirah Beach Residence (JBR), Dubai. JBR is one of Dubai''s most popular beachfront communities, offering direct beach access, vibrant dining and entertainment options, and stunning sea views. The area is highly sought after by both residents and tourists, ensuring strong rental demand.',
  'https://futurehomesturkey.com/en/estate/ad.php?id=4707',
  'https://cdn.futurehomesturkey.com/uploads/thumbs/pages/4707/general/apartment-322601.webp',
  '975000',
  'Apartments',
  '2+1 <> 4+1',
  '2 <> 4',
  '30/01/2026',
  '130 <> 290',
  '30',
  '0',
  'Anna Karlsson',
  '+90 552 303 27 50',
  '10058',
  'Under Construction',
  ARRAY[
    'https://cdn.futurehomesturkey.com/uploads/pages/4707/general/apartment-322601.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4707/interior/apartment-322602.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4707/interior/apartment-322603.webp',
    'https://cdn.futurehomesturkey.com/uploads/pages/4707/plan/apartment-322604.webp'
  ],
  '2+1 (Flat) - 130m² - €975,000; 3+1 (Flat) - 200m² - €1,450,000; 4+1 (Flat) - 290m² - €2,100,000',
  'Jumeirah Beach Residence',
  'Sea View,Beach Access,Resort Style Living,Infinity Pool,Beach Club,Water Sports,Marina Walk,The Walk JBR,Retail Outlets,Restaurants,24/7 Security,Luxury,From Developer,Under Construction'
);