-- Import existing testimonials data
INSERT INTO public.testimonials (customer_name, review_text, rating, property_type, location) VALUES
('Mrs. Cansel & Mr. Ihsan', 'Happy customers who bought an apartment from Antalya, Altıntaş and received their title deeds.', 5, 'apartment', 'Antalya, Altıntaş'),
('İbrahim', 'Happy customer who bought an apartment in Mersin from our company and received his title deed!', 5, 'apartment', 'Mersin'),
('Charlie', 'Happy customer who bought an apartment in Mersin, Erdemli from our company.', 5, 'apartment', 'Mersin, Erdemli'),
('Josef', 'Happy customer who bought several apartments from our company in Antalya, Altıntaş.', 5, 'apartment', 'Antalya, Altıntaş'),
('Mahnoor', 'Happy customer who bought a 1+1 apartment in Antalya, Altıntaş from our company.', 5, 'apartment', 'Antalya, Altıntaş'),
('Gönül', 'Happy customer who bought a land in Antalya, Döşemealtı from our company.', 5, 'land', 'Antalya, Döşemealtı'),
('Turgay', 'Happy customer who bought an apartment from our company in Antalya and received his title deed.', 5, 'apartment', 'Antalya'),
('Turgut', 'Happy customer who bought an apartment in Antalya, Altıntaş from our company and received his title deed.', 5, 'apartment', 'Antalya, Altıntaş'),
('Mert', 'Happy customer who bought an apartment from our company in Antalya.', 5, 'apartment', 'Antalya'),
('Salih', 'Happy customers who bought 3+1 apartment from at Dösemealti, Antalya from our company.', 5, 'apartment', 'Dösemealti, Antalya'),
('Sofiane & Yacine Belhadef', 'Happy customers who bought 2+1 apartment from our company and receiving his title deed this week.', 5, 'apartment', null),
('Ghursaran', 'Happy customer who bought apartment from Dubai from our company.', 5, 'apartment', 'Dubai'),
('Amir', 'Happy customer who bought 2 apartment from our company and receiving his title deed this week.', 5, 'apartment', null),
('Utku', 'Happy customer who bought 2+1 flat in Antalya.', 5, 'apartment', 'Antalya'),
('Abdul', 'Bought apartment from our company and receiving his title deed this week.', 5, 'apartment', null),
('Shelina', 'Happy Customer who bought an apartment from our Company in Antalya.', 5, 'apartment', 'Antalya'),
('Azatullah', 'Happy Customer purchased a 2+1 apartment and a 1+1 apartment in Antalya from our company.', 5, 'apartment', 'Antalya'),
('Oğuzhan', 'Happy Customer purchased a duplex apartment in Antalya from our company and received his title deed within one week.', 5, 'duplex apartment', 'Antalya'),
('Halima', 'Happy customer who bought 1+1 fully furnished apartment in Konyaaltı, Antalya from Future Homes', 5, 'apartment', 'Konyaaltı, Antalya'),
('Mehmet', 'Happy customer who bought 2+1 apartment in Antalya from our company', 5, 'apartment', 'Antalya'),
('Mustafa', 'I am very happy that i bought apartment from this company and i received my title deed within 1 week. Are you looking to buy from this company, do not hesitate.', 5, 'apartment', null),
('Aydogan', 'Happy customer who bought apartment from our company.', 5, 'apartment', null),
('Yana', 'Happy customer who bought apartment from Future Homes', 5, 'apartment', null),
('Luiza', 'I have bought two apartments this year in Mersin. I got help with everything. Many thanks to both Kim and Ali. They are skilled and efficient.', 5, 'apartment', 'Mersin'),
('Cuneyt', 'Would like to start off by giving a big Thank you to Future Homes. A very reliable trustable estate agency company. The service they pride is top level & there communication level is amazing. They are very helpful & always there for you. Highly recommend with an A* Ali Bey the owner of Future Homes & his team Tolga & Bariş Thank you guys so much for everything & hope to deal with you again. You guys treated me like i was apart of a family member of yours than a customer!', 5, 'apartment', null);