UPDATE public.courses SET final_pass_threshold = 70;

-- TURKEY
UPDATE public.courses SET final_quiz = '[
  {"q":"Which Turkish coast is most associated with high-end resort properties popular with European buyers?","options":["Black Sea coast","Aegean and Mediterranean coast","Eastern Anatolia","Marmara industrial belt"],"correctIndex":1,"explanation":"Antalya, Alanya, Bodrum and Fethiye on the Aegean/Mediterranean lead the foreign-buyer market."},
  {"q":"Foreign nationals buying property in Turkey must obtain which valuation document before title transfer?","options":["SPK-licensed property valuation report","Notarised rental contract","Municipal zoning letter","Embassy attestation"],"correctIndex":0,"explanation":"An SPK-licensed valuation report is mandatory for every foreign sale to combat under-declaration."},
  {"q":"What is the minimum real-estate investment for Turkish citizenship by investment (current rule)?","options":["USD 250,000","USD 400,000","USD 1,000,000","EUR 500,000"],"correctIndex":1,"explanation":"Since June 2022 the threshold is USD 400,000, held for at least 3 years."},
  {"q":"The official Turkish title deed is called:","options":["Tapu","Iskan","Numarataj","DASK"],"correctIndex":0,"explanation":"The Tapu is issued by the Land Registry (Tapu Müdürlüğü) and is the legal proof of ownership."},
  {"q":"Iskan is best described as:","options":["A purchase tax","The habitation/occupancy permit","Compulsory earthquake insurance","A buyer’s power of attorney"],"correctIndex":1,"explanation":"Iskan certifies the building meets code and may legally be lived in."},
  {"q":"Title-deed transfer tax (tapu harcı) in Turkey is typically:","options":["1% paid by buyer","4% split or negotiated between buyer and seller","8% paid by seller only","18% VAT on every sale"],"correctIndex":1,"explanation":"4% of the declared SPK value, in practice usually paid by the buyer or split."},
  {"q":"DASK is:","options":["A short-term rental licence","Compulsory earthquake insurance for the dwelling","A foreign-currency restriction","A municipal service fee"],"correctIndex":1,"explanation":"DASK (Zorunlu Deprem Sigortası) is required to connect utilities and complete title transfer."},
  {"q":"Foreign buyers must transfer the purchase funds into Turkey through:","options":["Cash carried at the border","A Turkish bank with a Döviz Alım Belgesi (DAB) FX certificate","Cryptocurrency wallet only","Their lawyer’s personal account"],"correctIndex":1,"explanation":"Funds must be converted to TRY at a Turkish bank, generating a DAB required for the Tapu office."},
  {"q":"Which city typically delivers the highest gross short-term rental yields for foreign-owned condos?","options":["Antalya/Alanya resort apartments","Eastern Anatolian villages","Cold Black Sea fishing towns","Industrial Bursa suburbs"],"correctIndex":0,"explanation":"Antalya and Alanya dominate Turkey’s short-let market thanks to year-round tourism."},
  {"q":"When reselling, capital gains tax on property is exempt after holding the asset for:","options":["1 year","3 years","5 years","10 years"],"correctIndex":2,"explanation":"After 5 years of ownership, individuals are exempt from CGT on residential property in Turkey."}
]'::jsonb WHERE country_code = 'turkey';

-- DUBAI
UPDATE public.courses SET final_quiz = '[
  {"q":"In Dubai, foreign nationals can own freehold property only in:","options":["Any emirate location","Designated freehold areas","Industrial zones only","Government-owned plots"],"correctIndex":1,"explanation":"Foreigners may buy freehold only in zones designated by Decree No. 3 of 2006 (e.g. Downtown, Marina, Palm)."},
  {"q":"The Dubai property regulator is:","options":["RERA, under DLD","DIFC","ADGM","Mubadala"],"correctIndex":0,"explanation":"RERA (Real Estate Regulatory Agency) operates under the Dubai Land Department (DLD)."},
  {"q":"Standard DLD transfer fee on a Dubai sale is:","options":["2%","4%","7.5%","10%"],"correctIndex":1,"explanation":"4% of the purchase price, customarily paid by the buyer."},
  {"q":"An off-plan purchase is protected by funds going into:","options":["The developer’s operating account","A RERA-approved escrow account","The buyer’s personal account","A Cayman trust"],"correctIndex":1,"explanation":"Law No. 8 of 2007 mandates RERA-supervised escrow for off-plan projects."},
  {"q":"A 2-year UAE residence visa is currently available to owners whose property value is at least:","options":["AED 200,000","AED 750,000","AED 2,000,000","AED 10,000,000"],"correctIndex":1,"explanation":"The 2-year investor visa starts at AED 750,000; the 10-year Golden Visa at AED 2,000,000."},
  {"q":"Annual personal income tax on Dubai rental income is:","options":["0%","5%","9%","20%"],"correctIndex":0,"explanation":"The UAE has no personal income tax; 9% corporate tax applies only to qualifying business income."},
  {"q":"Typical net rental yield in prime Dubai apartment areas is in the range of:","options":["1–2%","3–4%","5–8%","12–15%"],"correctIndex":2,"explanation":"Dubai is known for relatively high 5–8% net yields versus most global cities."},
  {"q":"The Oqood certificate represents:","options":["A final title deed","Off-plan interim registration with DLD","An eviction notice","A mortgage pre-approval"],"correctIndex":1,"explanation":"Oqood is the interim registration for off-plan units; the title deed replaces it on handover."},
  {"q":"Service charges in Dubai are:","options":["Optional and rare","Annual fees per sq ft set by the OA/RERA","Paid only by tenants","Included in the DLD fee"],"correctIndex":1,"explanation":"Owners pay annual service charges per sq ft, audited via RERA’s service-charge index."},
  {"q":"Short-term holiday letting in Dubai requires:","options":["No permit","A DTCM/DET holiday-home permit","An Abu Dhabi tourism licence","Only Airbnb verification"],"correctIndex":1,"explanation":"Operators must hold a Department of Economy & Tourism (DET) holiday-home permit."}
]'::jsonb WHERE country_code = 'dubai';

-- CYPRUS
UPDATE public.courses SET final_quiz = '[
  {"q":"Which part of Cyprus is in the EU and follows EU acquis on real-estate ownership?","options":["The Republic of Cyprus (south)","Northern Cyprus","Both equally","Neither"],"correctIndex":0,"explanation":"The Republic of Cyprus (south) is the EU member; the north is recognised only by Turkey."},
  {"q":"Non-EU buyers in the Republic of Cyprus need approval from:","options":["The Council of Ministers (District Office)","The European Commission","NATO","The Bank of Cyprus"],"correctIndex":0,"explanation":"Non-EU citizens require permission from the Council of Ministers, usually granted as a formality."},
  {"q":"Transfer fees on a resale property are charged on a sliding scale up to:","options":["1%","4%","8%","19%"],"correctIndex":2,"explanation":"Up to 8% on tranches above EUR 170k, with a 50% reduction in many cases."},
  {"q":"New properties from a VAT-registered seller carry standard VAT of:","options":["5%","9%","19%","23%"],"correctIndex":2,"explanation":"19% VAT, with a reduced 5% rate available on a primary residence up to defined area/value limits."},
  {"q":"Permanent Residency by Investment in Cyprus currently requires a minimum property investment of:","options":["EUR 100,000","EUR 300,000 + VAT","EUR 1,000,000","EUR 2,500,000"],"correctIndex":1,"explanation":"Category 6.2 fast-track PR requires a EUR 300,000 (plus VAT) new-build investment."},
  {"q":"Rental income for individuals is taxed under:","options":["A flat 0% rate","Personal income tax bands + 3% Special Defence Contribution","Only municipal tax","Corporate tax only"],"correctIndex":1,"explanation":"Rental income is subject to PIT plus 3% SDC on 75% of gross rent for tax-resident domiciled persons."},
  {"q":"The 60-day tax-residency rule lets you become Cyprus tax resident if you, among other tests:","options":["Spend at least 60 days, maintain a home, do business/employment, and are not tax resident elsewhere","Only spend 60 days, no other tests","Only buy property","Only register a company"],"correctIndex":0,"explanation":"All four conditions must be met to qualify under the 60-day rule."},
  {"q":"Cyprus title deeds are issued by:","options":["Land Registry Department (DLS)","The municipality","The developer","The Central Bank"],"correctIndex":0,"explanation":"DLS issues the Title Deed; the Sales Contract should be stamped and lodged within 6 months."},
  {"q":"Which coastal city is most associated with high-end seafront apartments and Russian/Israeli demand?","options":["Limassol","Paphos","Larnaca","Nicosia"],"correctIndex":0,"explanation":"Limassol commands the strongest premiums and the largest expat investor base."},
  {"q":"Typical gross long-term rental yield in coastal Cyprus is approximately:","options":["1–2%","4–6%","10–12%","15–20%"],"correctIndex":1,"explanation":"4–6% gross is typical for long-term lets in Limassol/Paphos/Larnaca."}
]'::jsonb WHERE country_code = 'cyprus';

-- BALI
UPDATE public.courses SET final_quiz = '[
  {"q":"Foreigners CANNOT directly own which type of Indonesian land?","options":["Hak Milik (freehold)","Hak Pakai (right to use)","Hak Sewa (leasehold)","All forms of usage rights"],"correctIndex":0,"explanation":"Hak Milik is reserved for Indonesian citizens; foreigners use Hak Pakai or long-term leasehold."},
  {"q":"The most common legal structure foreigners use to control villa investments in Bali is:","options":["Hak Pakai or long-term leasehold (often via PT PMA)","Hak Milik in their own name","UK-style freehold","A simple verbal agreement"],"correctIndex":0,"explanation":"Leasehold (25–30 years, extendable) and Hak Pakai via PT PMA are the standard secure routes."},
  {"q":"A PT PMA is:","options":["A type of Indonesian title deed","A foreign-owned limited company","A short-stay visa","A property insurance product"],"correctIndex":1,"explanation":"PT Penanaman Modal Asing — a foreign-investment company that can hold Hak Pakai or HGB."},
  {"q":"Long-term land lease terms in Bali are typically:","options":["1–3 years","5–10 years","25–30 years (extendable)","99 years freehold"],"correctIndex":2,"explanation":"25–30 years with extension options is the standard market norm."},
  {"q":"BPHTB land acquisition tax in Indonesia is approximately:","options":["1%","2.5%","5%","11%"],"correctIndex":2,"explanation":"BPHTB is typically 5% of the transaction value above the regional NPOPTKP threshold."},
  {"q":"PPh (income tax on sale by seller) on transferred property is generally:","options":["2.5%","10%","15%","20%"],"correctIndex":0,"explanation":"Final PPh is 2.5% of the gross transaction value for the seller."},
  {"q":"VAT (PPN) on the purchase of a new property from a developer is currently:","options":["0%","5%","11%","20%"],"correctIndex":2,"explanation":"PPN is 11% (rising as scheduled by law); resale between individuals is normally outside PPN."},
  {"q":"Net rental yields on well-managed Bali villas typically range around:","options":["1–2%","3–5%","6–12%","20–30%"],"correctIndex":2,"explanation":"Short-term holiday villas commonly achieve 6–12% net depending on location and management."},
  {"q":"To legally operate a short-term villa rental in Bali, the property normally needs:","options":["Just a sign at the gate","A Pondok Wisata (or hotel) licence and NPWP tax number","A foreign visa only","An EU passport"],"correctIndex":1,"explanation":"A Pondok Wisata permit (for private villas) plus tax registration are required for legal short-lets."},
  {"q":"Currency you should keep most operating funds in for a Bali rental business is:","options":["IDR (Rupiah) – local operating costs are in IDR","JPY","CHF","Gold only"],"correctIndex":0,"explanation":"Costs, staff and taxes are in IDR; FX exposure is reduced by holding working capital locally."}
]'::jsonb WHERE country_code = 'bali';